{dede:field name='keywords'}江西,事业单位招聘{/dede:field}
{dede:field name='description'}2015年江西九江修水县招聘事业单位工作人员公告（76名）{/dede:field}
{dede:field name='title'}2015年江西九江修水县招聘事业单位工作人员公告（76名）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　江西备考交流QQ群：186502481<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/jiangxi/sy" target="_blank"><span style="color: #0000ff">2015年江西省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年江西九江修水县招聘事业单位工作人员公告（76名）</h2>
<p>
	　　修水县2015年上半年面向社会公开招聘事业单位工作人员76名，网上报名时间：2015年4月20日8:00至4月22日17:00，详情请查阅九江市人事考试网(http://0792.jxpta.com/news/1_1041.html)或九江市人力资源和社会保障局网(http://www.jjrs.gov.cn/Rea_400.asp?ID=6016)。</p>
<p style="text-align: right;">
	　　修水县人力资源和社会保障局</p>
<p style="text-align: right;">
	　　2015年4月8日</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
