<?php
$z[0]=Array("field","江西,事业单位招聘",0,66);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2015年江西九江修水县招聘事业单位工作人员公告（76名）",68,187);
$z[1][4]['name']="description";
$z[2]=Array("field","2015年江西九江修水县招聘事业单位工作人员公告（76名）",189,302);
$z[2][4]['name']="title";
$z[3]=Array("field","",304,343);
$z[3][4]['name']="writer";
$z[4]=Array("field","",345,384);
$z[4][4]['name']="source";
$z[5]=Array("field","",386,426);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<span style=\"color: #ff0000\">　　江西备考交流QQ群：186502481<br />\r\n<span style=\"color: #0000ff\"><strong>　　</strong></span></span><strong><span style=\"color: #0000ff\">备考推荐：</span><a href=\"http://v.huatu.com/jiangxi/sy\" target=\"_blank\"><span style=\"color: #0000ff\">2015年江西省事业单位考试名师网络课程班</span></a></strong>\r\n<hr />\r\n<h2 style=\"text-align: center;\">\r\n	2015年江西九江修水县招聘事业单位工作人员公告（76名）</h2>\r\n<p>\r\n	　　修水县2015年上半年面向社会公开招聘事业单位工作人员76名，网上报名时间：2015年4月20日8:00至4月22日17:00，详情请查阅九江市人事考试网(http://0792.jxpta.com/news/1_1041.html)或九江市人力资源和社会保障局网(http://www.jjrs.gov.cn/Rea_400.asp?ID=6016)。</p>\r\n<p style=\"text-align: right;\">\r\n	　　修水县人力资源和社会保障局</p>\r\n<p style=\"text-align: right;\">\r\n	　　2015年4月8日</p>\r\n\r\n</section><!--文章正文结束-->",428,1467);
$z[6][4]['name']="body";
$z[7]=Array("field","",1469,1508);
$z[7][4]['name']="litpic";

?>