{dede:noteinfo notename="华图教育" channelid="1" macthtype="string"
refurl="http://" sourcelang="big5" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.huatu.com/list/4554_(*).html"
startid="2" endid="3" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<!--40条-->{/dede:areastart}
    {dede:areaend}<!--40条-->{/dede:areaend}
{/dede:listrule}
