{dede:noteinfo notename="公务员" channelid="1" macthtype="string"
refurl="" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.huatu.com/list/4598_(*).html"
startid="1" endid="3" addv="1" urlrule="area"
 musthas="" nothas="list" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ul class="list07">{/dede:areastart}
    {dede:areaend}<ul class="page clearfix">{/dede:areaend}
{/dede:listrule}
