{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江杭州市西湖区文鼎苑幼儿园招聘公告{/dede:field}
{dede:field name='title'}2015年浙江杭州市西湖区文鼎苑幼儿园招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江杭州市西湖区文鼎苑幼儿园招聘公告</h2>
<p>
	　　杭州市西湖区文鼎苑幼儿园是一所隶属于西湖区教育局的甲级幼儿园和省一级幼儿园。地处在古墩路635号文鼎苑小区内，于2010年9月开园，共设有16个班级的规模。幼儿园秉承&ldquo;鼎真、鼎善、鼎美&rdquo;的办园宗旨，创建&ldquo;七彩阳光社团&rdquo;，致力于打造象阳光般的幼儿教育：让孩子透明、纯净，使家长温暖、幸福，促社会和谐、 满意。</p>
<p>
	　　现因幼儿园发展需要，诚聘以下人员：</p>
<p>
	　<strong>　一、 幼儿教师若干名</strong></p>
<p>
	　　应聘条件：</p>
<p>
	　　1.热爱幼教事业，工作责任心强、善于合作、乐于奉献。</p>
<p>
	　　2.学前教育大专及以上学历，有教师资格证，在职或应届毕业生均可。</p>
<p>
	　　3.有工作经验、获区级以上各类荣誉或优秀应届毕业生优先。</p>
<p>
	　　4.应聘者需提供本人简历，学历、普通话、计算机等级证书，荣誉证书等相关证件的原件和复印件。</p>
<p>
	　<strong>　二、厨师一名：</strong></p>
<p>
	　　应聘条件：</p>
<p>
	　　热爱本职工作，身体健康，有责任心，能吃苦耐劳，有厨师等级证书。</p>
<p>
	<strong>　　三、保育员若干名：</strong></p>
<p>
	　　应聘条件：</p>
<p>
	　　身体健康，责任心强，喜欢孩子，会说普通话，善于沟通，有保育员上岗证优先。</p>
<p>
	　　真诚欢迎您的加入，我们将为您提供发展的平台!</p>
<p>
	<strong>　　四、 联系方式</strong>：</p>
<p>
	　　1、 联系电话： 88867690&mdash;81 15869150715</p>
<p>
	　　2、 联系地址：杭州市西湖区古墩路635号(文鼎苑小区东门口)。</p>
<p>
	　　3、 联系人：马老师</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
