{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江嘉兴海宁市园林市政局招聘3名短期临时驾驶员公告{/dede:field}
{dede:field name='title'}2015年浙江嘉兴海宁市园林市政局招聘3名短期临时驾驶员公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江嘉兴海宁市园林市政局招聘3名短期临时驾驶员公告</h2>
　　海宁市园林市政局为海宁市住房和城乡规划建设局下属公益一类事业单位，因工作需要,现面向社会公开招聘3名短期临时专职驾驶员。具体事项如下：<br />
<strong>　　一、招聘对象及条件</strong><br />
　　(一) 遵纪守法，作风正派，身体健康，吃苦耐劳，有较强责任心，热爱本职工作。<br />
　　(二)初中及以上文化程度，户籍不限，要求男性，年龄50周岁以下，在部队从事驾驶职业的转业(退伍)军人优先。<br />
　　(三)取得准驾车型为B照及以上的中华人民共和国机动车辆驾驶证(军证必须换为地方证)，具有5年以上驾龄，驾驶技术熟练，期间未出现过重大交通安全事故。<br />
　　(四)无违法违纪行为，无不良记录。<br />
　　(五)应聘人员能自行海宁城区解决食宿，并熟悉城区及周边交通路线。<br />
<strong>　　三、报名及资格审查</strong><br />
　　(一)报名<br />
　　1、报名时间：2015年4月14日-2015年4月16日上午8：30-11：30、下午13：30-17：00。<br />
　　2、报名地点：海宁市园林市政局304办公室(南苑路400号)，联系电话：87216267<br />
　　3、报名需提供以下资料：<br />
　　(1)有效《居民身份证》(暂住证)、户口本原件及复印件;<br />
　　(2)有效《机动车驾驶证》原件及复印件;<br />
　　(3)本人近期免冠1寸彩照2张;<br />
　　(4)是退伍军人的，需持军人退伍证。<br />
　　(二) 录用办法<br />
　　1、资格审查：应聘人员凭要求提供的资料进行报名。资格审查通过者填写《海宁市园林市政局公开招聘专职驾驶员报名表》。<br />
　　2、考试：资格审查合格者需通过实际驾驶操作方式进行技能测试，测试合格者，方能录用，如未按时参加者视为自动弃权。<br />
　　3、体检：根据技能测试成绩名次，按拟招聘人数1：1比例确定参加体检的人选。<br />
　　检标准参照《浙江省人事厅、浙江省卫生厅转发人事部卫生部关于印发&lt;公务员录用体检通用标准(试行)&gt;的通知》(浙人公〔2005〕 68号)及人力资源社会保障部、卫生部《修订&lt;公务员录用体检通用标准(试行)&gt;及&lt;公务员录用体检操作手册(试行)&gt;》等政策执行。报考人员不按规定的时间、地点参加体检的，视作放弃体检;凡体检不合格的，不予录用，并按成绩排名依次进行递补。<br />
<strong>　　四、聘用管理及待遇</strong><br />
　　录用后实行试用期制度，试用期为1个月，试用期间工资按试用期待遇发放;试用期满后经单位考核不合格者作辞退处理。<br />
　　海宁市园林市政局公开招聘专职驾驶员报名表<br />
<table align="left" border="1" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width:78px;height:43px;">
				&nbsp;姓名</td>
			<td style="width:83px;height:43px;">
				&nbsp;</td>
			<td style="width:46px;height:43px;">
				性别</td>
			<td style="width:73px;height:43px;">
				&nbsp;</td>
			<td style="width:72px;height:43px;">
				出生年月</td>
			<td colspan="3" style="width:167px;height:43px;">
				&nbsp;</td>
			<td rowspan="3" style="width:115px;height:43px;">
				照片</td>
		</tr>
		<tr>
			<td style="width:78px;height:43px;">
				政治面貌</td>
			<td style="width:83px;height:43px;">
				&nbsp;</td>
			<td style="width:46px;height:43px;">
				籍贯</td>
			<td style="width:73px;height:43px;">
				&nbsp;</td>
			<td style="width:72px;height:43px;">
				民&nbsp; 族</td>
			<td colspan="3" style="width:167px;height:43px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:43px;">
				毕业时间</td>
			<td style="width:83px;height:43px;">
				&nbsp;</td>
			<td style="width:46px;height:43px;">
				学历</td>
			<td style="width:73px;height:43px;">
				&nbsp;</td>
			<td style="width:72px;height:43px;">
				婚姻<br />
				状况</td>
			<td colspan="3" style="width:167px;height:43px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:43px;">
				驾驶证准驾型号</td>
			<td style="width:83px;height:43px;">
				&nbsp;</td>
			<td style="width:46px;height:43px;">
				驾驶年限</td>
			<td colspan="2" style="width:145px;height:43px;">
				&nbsp;</td>
			<td style="width:72px;height:43px;">
				身份证号码</td>
			<td colspan="3" style="width:210px;height:43px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:43px;">
				毕业院校</td>
			<td colspan="5" style="width:347px;height:43px;">
				&nbsp;</td>
			<td style="width:95px;height:43px;">
				健康状况</td>
			<td colspan="2" style="width:116px;height:43px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:43px;">
				现工作单位</td>
			<td colspan="5" style="width:347px;height:43px;">
				&nbsp;</td>
			<td style="width:95px;height:43px;">
				参加工作时间</td>
			<td colspan="2" style="width:116px;height:43px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:43px;">
				应聘单位</td>
			<td colspan="5" style="width:347px;height:43px;">
				&nbsp;</td>
			<td style="width:95px;height:43px;">
				应聘岗位</td>
			<td colspan="2" style="width:116px;height:43px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:43px;">
				联系地址</td>
			<td colspan="5" style="width:347px;height:43px;">
				&nbsp;</td>
			<td style="width:95px;height:43px;">
				邮&nbsp;&nbsp;&nbsp; 编</td>
			<td colspan="2" style="width:116px;height:43px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:43px;">
				联系电话</td>
			<td colspan="5" style="width:347px;height:43px;">
				&nbsp;</td>
			<td style="width:95px;height:43px;">
				联 系 人</td>
			<td colspan="2" style="width:116px;height:43px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:252px;">
				本人简历(从初中起)</td>
			<td colspan="8" style="width:557px;height:252px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:78px;height:93px;">
				备 注</td>
			<td colspan="8" style="width:557px;height:93px;">
				本人承诺：本表所填内容真实可靠，如有虚假，本人愿意承担一切责任。<br />
				（其它承诺事项）：<br />
				承诺人签字：</td>
		</tr>
		<tr height="0">
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
		</tr>
	</tbody>
</table>
<div style="text-align: right;">
	　　海宁市园林市政局<br />
	　　2015年3月5日</div>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
