{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江省台州临海市人民法院招聘2名编外合同制速录员公告{/dede:field}
{dede:field name='title'}2015年浙江省台州临海市人民法院招聘2名编外合同制速录员公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江省台州临海市人民法院招聘2名编外合同制速录员公告</h2>
<p>
	　　因工作需要，现拟向社会公开招聘编外合同制速录员2名(纳入临海市新世纪人才开发有限公司派遣，安排在杜桥法庭工作)，现将有关事项公告如下：</p>
<p>
	　<strong>　一、招聘条件：</strong></p>
<p>
	　　1、拥护中国共产党领导，遵纪守法，品行端正，无不良记录;</p>
<p>
	　　2、年龄在35周岁以下(1980年4月7日以后出生)，身体健康;</p>
<p>
	　　3、高中以上学历，具有较强的文字录入能力。</p>
<p>
	　　4、户籍要求：临海市。</p>
<p>
	　<strong>　二、报考程序与审核</strong></p>
<p>
	　　要求本人在规定时间内到现场报名，填写报名表。</p>
<p>
	　　1、报名时间：2015年4月8日至4月16日;</p>
<p>
	　　2、报名地点：临海法院政治处819室， 联系电话：85136992;</p>
<p>
	　　3、报名时需提供以下材料：身份证、户口簿、学历证书原件与复印件;2寸近期彩照二张;</p>
<p>
	　　4、经审核，符合条件者参加考试。</p>
<p>
	<strong>　　三、考试方式</strong></p>
<p>
	　　测试分技能测试和面试。</p>
<p>
	<strong>　　四、录用程序</strong></p>
<p>
	　　技能测试成绩要求每分钟录入60字以上的进入面试，根据面试成绩录取，第1、2名进入体检，经体检、政审合格者予以录用。被录用者，签订3年期合同，其中试用期为6个月。</p>
<p>
	&nbsp;</p>
<p style="text-align: right;">
	　　2015年4月8日</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
