{dede:field name='keywords'}江西,事业单位招聘{/dede:field}
{dede:field name='description'}2015年江西陶瓷工艺美术职业技术学院招聘高层次人才公告{/dede:field}
{dede:field name='title'}2015年江西陶瓷工艺美术职业技术学院招聘高层次人才公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　江西备考交流QQ群：186502481<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/jiangxi/sy" target="_blank"><span style="color: #0000ff">2015年江西省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年江西陶瓷工艺美术职业技术学院招聘高层次人才公告</h2>
　　江西陶瓷工艺美术职业技术学院是经江西省人民政府批准、国家教育部备案的公办全日制普通高等示范性院校，直属省教育厅管理的副厅级单位。学院是一所以陶瓷工程、艺术设计类专业为主，涉及文学、理学、工学、商学、管理学等多门类学科的高职院校。学校现有教职工424人，其中教授30人，副教授47人，国家高等院校教学名师1人，国务院特殊津贴获得者2人，国家级工艺美术大师5人，省级工艺美术大师5人，江西陶瓷美术家3人，高级工艺美术师9人，全国行业专业教学指导委员会委员6人，省级学科带头人1人，省级教学名师5人，省级中青年骨干教师16人，入选&ldquo;江西省新世纪百千万人才工程&rdquo;2人。省级教学团队3个。<br />
　　为适应学院规模不断扩大和实现内涵式发展战略目标，现面向社会公开招聘专任教师、辅导员及行政管理人员。<br />
　　<strong>一、招聘岗位、人数和条件</strong><br />
<table border="1" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width:58px;height:41px;">
				<strong>部门</strong></td>
			<td style="width:113px;height:41px;">
				<strong>岗位名称</strong></td>
			<td style="width:47px;height:41px;">
				<strong>招聘人数</strong></td>
			<td style="width:257px;height:41px;">
				<strong>岗位条件</strong></td>
		</tr>
		<tr>
			<td rowspan="3" style="width:58px;height:64px;">
				材料与机械工程学院</td>
			<td style="width:113px;height:64px;">
				材料工程技术专业（陶瓷工程方向）辅导员岗位</td>
			<td style="width:47px;height:64px;">
				1</td>
			<td style="width:257px;height:64px;">
				材料工程专业、玻璃与陶瓷材料专业、材料科学与工程专业、材料学专业（均为陶瓷材料方向）全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:83px;">
				热能工程（陶瓷热能装备及控制技术方向）辅导员岗位</td>
			<td style="width:47px;height:83px;">
				1</td>
			<td style="width:257px;height:83px;">
				热能工程专业（陶瓷方向）全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:73px;">
				汽车检测与维修方向教学岗位</td>
			<td style="width:47px;height:73px;">
				1</td>
			<td style="width:257px;height:73px;">
				汽车工程或车辆工程专业全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:58px;height:50px;">
				数字艺术学院</td>
			<td style="width:113px;height:50px;">
				影视动画专业教学岗位</td>
			<td style="width:47px;height:50px;">
				1</td>
			<td style="width:257px;height:50px;">
				动画或动漫专业（三维方向）全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:71px;">
				摄影摄像技术专业辅导员岗位</td>
			<td style="width:47px;height:71px;">
				1</td>
			<td style="width:257px;height:71px;">
				摄影摄像研究方向全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td rowspan="5" style="width:58px;height:71px;">
				陶瓷艺术学院</td>
			<td style="width:113px;height:71px;">
				雕刻艺术与家具设计专业教学岗位</td>
			<td style="width:47px;height:71px;">
				1</td>
			<td style="width:257px;height:71px;">
				家具设计与工程专业（艺术类）全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:61px;">
				陶瓷艺术设计专业教学岗位</td>
			<td style="width:47px;height:61px;">
				1</td>
			<td style="width:257px;height:61px;">
				陶瓷艺术设计专业方向全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:73px;">
				文物鉴定与修复（古陶瓷方向）教学岗位</td>
			<td style="width:47px;height:73px;">
				2</td>
			<td style="width:257px;height:73px;">
				陶瓷考古或古陶瓷鉴定专业方向的全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:68px;">
				雕刻艺术与家具设计专业辅导员岗位</td>
			<td style="width:47px;height:68px;">
				1</td>
			<td style="width:257px;height:68px;">
				家具设计与工程专业（艺术类）全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:70px;">
				陶瓷艺术设计专业辅导员岗位</td>
			<td style="width:47px;height:70px;">
				1</td>
			<td style="width:257px;height:70px;">
				陶瓷艺术设计专业方向全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td rowspan="3" style="width:58px;height:52px;">
				设计艺术学院</td>
			<td style="width:113px;height:52px;">
				产品造型设计专业教学岗位</td>
			<td style="width:47px;height:52px;">
				1</td>
			<td style="width:257px;height:52px;">
				产品设计（艺术类）专业或工业设计（艺术类）专业全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:52px;">
				环境艺术设计专业教学岗位</td>
			<td style="width:47px;height:52px;">
				1</td>
			<td style="width:257px;height:52px;">
				室内设计（艺术类）专业或景观设计（艺术类）专业全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:113px;height:52px;">
				环境艺术设计专业辅导员岗位</td>
			<td style="width:47px;height:52px;">
				1</td>
			<td style="width:257px;height:52px;">
				室内设计（艺术类）或景观设计（艺术类）专业全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:58px;height:52px;">
				监察审计处</td>
			<td style="width:113px;height:52px;">
				监察审计岗位</td>
			<td style="width:47px;height:52px;">
				1</td>
			<td style="width:257px;height:52px;">
				土木工程专业、土木工程施工技术与管理专业（均为工程造价方向）全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；中共党员；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:58px;height:52px;">
				财务处</td>
			<td style="width:113px;height:52px;">
				财务会计岗位</td>
			<td style="width:47px;height:52px;">
				1</td>
			<td style="width:257px;height:52px;">
				财务会计专业、会计专业、财务管理专业全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:58px;height:52px;">
				五年制高职部</td>
			<td style="width:113px;height:52px;">
				陶瓷艺术专业教学岗位</td>
			<td style="width:47px;height:52px;">
				2</td>
			<td style="width:257px;height:52px;">
				陶瓷艺术设计专业方向全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:58px;height:52px;">
				院长办公室</td>
			<td style="width:113px;height:52px;">
				文秘档案管理岗位</td>
			<td style="width:47px;height:52px;">
				1</td>
			<td style="width:257px;height:52px;">
				中国语言文学专业、档案管理专业全日制统招研究生学历、硕士及以上学位（含2015年应届毕业生）；中共党员；1980年1月1日以后出生。</td>
		</tr>
	</tbody>
</table>
　　备注：(1)国外硕士须经教育部留学服务中心认证;
</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
