<?php
$z[0]=Array("sppage","",0,73);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.ikanchai.com/2015/0420/16249.shtml",75,155);
$z[2]=Array("keywordtrim","",157,194);
$z[3]=Array("descriptiontrim","",196,241);
$z[4]=Array("item","\r\n   {dede:match}<h3>[内容]</h3>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",243,399);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}<span class=\"spanimg1\">作者：[内容]</span>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",401,588);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",590,730);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}@me=GetMkTime(@me);{/dede:function}\r\n",732,892);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"article-content fontSizeSmall BSHARE_POP\">[内容]<div class=\"mood\">{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",894,1114);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>