{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江丽水市第二人民医院招聘财务公告{/dede:field}
{dede:field name='title'}2015年浙江丽水市第二人民医院招聘财务公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江丽水市第二人民医院招聘财务公告</h2>
　　我单位因业务发展需要，现面向社会公开招聘财务人员1 名，要求大专及以上学历，需有会计上岗证，具有财务相关工作经验两年以上(医院相关工作经验优先)，年龄 40 岁以下(1975年4月后出生)，男女不限。有意应聘者请携带报名表、个人简历、毕业证、会计上岗证、身份证等原件与复印件，一寸免冠照片一张，于 2015年4月10日至17日到二院人事科报名。<br />
　　联系电话：0578-2152196<br />
　　联系地址：丽水市大洋路115号<br />
　　丽水市第二人民医院报名表<br />
<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width:92px;height:35px;">
				姓名</td>
			<td style="width:114px;height:35px;">
				&nbsp;</td>
			<td colspan="2" style="width:47px;height:35px;">
				性别</td>
			<td style="width:69px;height:35px;">
				&nbsp;</td>
			<td colspan="3" style="width:92px;height:35px;">
				出生年月</td>
			<td style="width:103px;height:35px;">
				&nbsp;</td>
			<td rowspan="4" style="width:80px;height:35px;">
				照<br />
				&nbsp;<br />
				片</td>
		</tr>
		<tr>
			<td style="width:92px;height:35px;">
				民族</td>
			<td style="width:114px;height:35px;">
				&nbsp;</td>
			<td colspan="2" style="width:47px;height:35px;">
				籍贯</td>
			<td style="width:69px;height:35px;">
				&nbsp;</td>
			<td colspan="3" style="width:92px;height:35px;">
				政治面貌</td>
			<td style="width:103px;height:35px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:92px;height:35px;">
				身份证号码</td>
			<td style="width:114px;height:35px;">
				&nbsp;</td>
			<td colspan="2" style="width:47px;height:35px;">
				健康<br />
				状况</td>
			<td style="width:69px;height:35px;">
				&nbsp;</td>
			<td colspan="2" style="width:69px;height:35px;">
				联系<br />
				电话</td>
			<td colspan="2" style="width:126px;height:35px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:92px;height:35px;">
				学历学位</td>
			<td colspan="2" style="width:149px;height:35px;">
				&nbsp;</td>
			<td colspan="3" style="width:92px;height:35px;">
				毕业院校时间及专业</td>
			<td colspan="3" style="width:183px;height:35px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:92px;height:35px;">
				通讯地址</td>
			<td colspan="9" style="width:505px;height:35px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:92px;height:173px;">
				学<br />
				习<br />
				工<br />
				作<br />
				简<br />
				历</td>
			<td colspan="9" style="width:505px;height:173px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:92px;height:20px;">
				个人特长</td>
			<td colspan="9" style="width:505px;height:20px;">
				&nbsp;<br />
				&nbsp;<br />
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:92px;height:80px;">
				曾获荣誉</td>
			<td colspan="9" style="width:505px;height:80px;">
				&nbsp;<br />
				&nbsp;<br />
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:92px;height:61px;">
				初审意见</td>
			<td colspan="9" style="width:505px;height:61px;">
				&nbsp;<br />
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:92px;height:61px;">
				审核意见</td>
			<td colspan="9" style="width:505px;height:61px;">
				&nbsp;<br />
				&nbsp;</td>
		</tr>
		<tr height="0">
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
		</tr>
	</tbody>
</table>
<div style="text-align: right;">
	　　丽水市第二人民医院<br />
	　　2015年4月9日</div>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
