{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建泉州惠安县医院医生招聘公告{/dede:field}
{dede:field name='title'}2015年福建泉州惠安县医院医生招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建泉州惠安县医院医生招聘公告</h2>
<p>
	　　福建省惠安县医院创办于1902年，院址位于县城中心，是一所二级甲等综合性医院。编制床位600张，现有职工700余人，其中主任医师34人，副主任医(护、技)师73人，中级职称206人，系福建医科大学、福建中医学院、福建莆田学院、泉州医高专等院校的教学医院。医院设有15个临床科室、14 个二级专业组、16个医技科室和11个职能科室。</p>
<p>
	　　本次招聘岗位不占用惠安县医院单位核定的事业编制，人员聘用后为事业单位编制外工作人员。</p>
<p>
	　　现因业务发展需要，拟招聘院聘人员如下：</p>
<p>
	　　<strong>一、 临床医师</strong>(内、外科专业医师各3名，儿科医师2名，重症医学2名，康复医学1名)</p>
<p>
	　　(1)临床医学专业，本科以上学历，持有本执业范围的医师资格证书;</p>
<p>
	　　(2)工作认真负责，有良好的沟通能力和亲和力;</p>
<p>
	　　(3)办理&ldquo;五险&rdquo;，可为外地员工提供免费住宿;</p>
<p>
	　　(4)参照在编同等级医师待遇。</p>
<p>
	　<strong>　二、&ldquo;120&rdquo;急救中心医师3名</strong></p>
<p>
	　　(1)临床医学专业，中专以上学历，持有执业医师资格证书;</p>
<p>
	　　(2)工作认真负责，有良好的沟通能力和亲和力;</p>
<p>
	　　(3)办理&ldquo;五险&rdquo;，可为外地员工提供免费住宿;</p>
<p>
	　　(4)薪酬面议。</p>
<p>
	　　<strong>三、助理医师15名</strong></p>
<p>
	　　(1)临床医学专业，大专以上学历;</p>
<p>
	　　(2)工作认真负责，有病历书写功底;</p>
<p>
	　　(3)办理&ldquo;五险&rdquo;;</p>
<p>
	　　(4)薪酬2000/月，表现优秀另有奖励。</p>
<p>
	　　<strong>四、体检部医师2名</strong></p>
<p>
	　　(1)全科医师，大专以上学历，持有执业医师资格证书;</p>
<p>
	　　(2)工作认真负责，有良好的沟通能力和亲和力;</p>
<p>
	　　(3)办理&ldquo;五险&rdquo;;</p>
<p>
	　　(4)薪酬面议。</p>
<p>
	　　联系人：陈小姐</p>
<p>
	　　联系电话：0595&mdash;68191015</p>
<p>
	　　电子邮箱：haxyy182@126.com</p>
<p>
	　　发布于：2015/4/7</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
