{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建厦门国际旅行卫生保健中心非编人员招聘4人公告{/dede:field}
{dede:field name='title'}2015年福建厦门国际旅行卫生保健中心非编人员招聘4人公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建厦门国际旅行卫生保健中心非编人员招聘4人公告</h2>
<p>
	　　厦门国际旅行卫生保健中心是中华人民共和国厦门出入境检验检疫局直属具有独立法人资格的事业单位，主要负责传染病监测与健康体检、旅行预防接种、卫生保健咨询、医疗保健门诊、医学媒介生物的监测与检测，为卫生检疫技术科研开发与技术服务、提供技术指导。</p>
<p>
	　　因工作需要，我中心拟面向社会公开招聘4名非在编工作人员。具体事项如下：</p>
<p>
	　<strong>　一、基本条件</strong></p>
<p>
	　　1、具有中华人民共和国国籍;</p>
<p>
	　　2、遵守中华人民共和国宪法、法律、法规，无犯罪记录;</p>
<p>
	　　3、遵守纪律，品行端正，职业道德良好;</p>
<p>
	　　4、身体健康，五官端正，能吃苦，服从工作安排，工作责任心强;</p>
<p>
	　　5、符合岗位招聘条件。</p>
<p>
	　<strong>　二、招聘岗位、人数及要求</strong></p>
<p>
	　　1、岗位：x光医生</p>
<p>
	　　人数：1名。</p>
<p>
	　　性别：不限。</p>
<p>
	　　年龄：不限。</p>
<p>
	　　学历要求：大学专科及以上学历。</p>
<p>
	　　专业要求：医学影像学等相关专业。</p>
<p>
	　　其他要求：具有执业医师资格。</p>
<p>
	　　2、岗位：B超医生</p>
<p>
	　　人数：1名。</p>
<p>
	　　性别：不限。</p>
<p>
	　　年龄：不限。</p>
<p>
	　　学历要求：大学专科及以上学历。</p>
<p>
	　　专业要求：临床医学、医学影像学等相关专业。</p>
<p>
	　　其他要求：具有执业医师资格。</p>
<p>
	　　3、 岗位：妇科医生</p>
<p>
	　　人数：1名。</p>
<p>
	　　性别：女。</p>
<p>
	　　年龄：不限。</p>
<p>
	　　学历要求：大学专科及以上学历。</p>
<p>
	　　专业要求：临床医学，妇产科学等相关专业。</p>
<p>
	　　其他要求：具有执业医师资格。</p>
<p>
	　　4、岗位：内科医生</p>
<p>
	　　人数：1名。</p>
<p>
	　　性别：不限。</p>
<p>
	　　年龄：不限。</p>
<p>
	　　学历要求：大学专科及以上学历。</p>
<p>
	　　专业要求：临床医学专业。</p>
<p>
	　　其他要求：具有执业医师资格，具有健康评估工作经验者优先。</p>
<p>
	<strong>　　三、应聘方法</strong></p>
<p>
	　　有意者请将电子版个人简历(附照片,含联系方式)发至 chenzibin@xmciq.gov.cn,并注明应聘的岗位，如应聘-X光医生-姓名，届时我中心将根据应聘者情况按招聘程序及相关要求，合适者通知面试。联系电话：0592-5678331。</p>
<p style="text-align: right;">
	　　厦门国际旅行卫生保健中心</p>
<p style="text-align: right;">
	　　2015年4月</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
