<?php
$z[0]=Array("noteinfo","",0,157);
$z[0][4]['notename']="公务员";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="regex";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"main1_L\">{/dede:areastart}\r\n    {dede:areaend}<div class=\"c_main1_R right\">{/dede:areaend}\r\n",161,621);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.eoffcn.com/gwy/kszx/gonggao/(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="3";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="kszx";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>