{dede:noteinfo notename="公务员" channelid="1" macthtype="regex"
refurl="http://" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.eoffcn.com/gwy/kszx/gonggao/(*).html"
startid="1" endid="3" addv="1" urlrule="area"
 musthas="kszx" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="main1_L">{/dede:areastart}
    {dede:areaend}<div class="c_main1_R right">{/dede:areaend}
{/dede:listrule}
