{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年厦门集美大学鳗鲡现代产业技术教育部工程研究中心招聘公告{/dede:field}
{dede:field name='title'}2015年厦门集美大学鳗鲡现代产业技术教育部工程研究中心招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年厦门集美大学鳗鲡现代产业技术教育部工程研究中心招聘公告</h2>
<p>
	　　因工作需要，拟向社会公开招聘鳗鲡现代产业技术教育部工程研究中心科辅人员1名，实行人事代理管理。招聘有关事项如下：</p>
<p>
	　<strong>　一、单位简介</strong></p>
<p>
	　　鳗鲡现代产业技术教育部工程研究中心是教育部于2009年8月批准立项建设的研发机构，主要开展鳗鱼现代产业工程化技术研发，促进鳗鱼产业及其他主要水产养殖品种产业的健康可持续发展。中心依托集美大学建设和管理。</p>
<p>
	　<strong>　二、招聘岗位</strong></p>
<p>
	　　鳗鲡现代产业技术教育部工程研究中心科辅人员1名。</p>
<p>
	　　<strong>三、招聘条件</strong></p>
<p>
	　　1、硕士研究生及以上学历，年龄30周岁以下。</p>
<p>
	　　2、制药工程或药学相关专业。</p>
<p>
	　　3、熟悉制药设备维护与保养，具备开展科学研究、技术开发、田间试验和应用推广工作的能力。</p>
<p>
	<strong>　　四、报名、资格审查及考核</strong></p>
<p>
	　　1.报名时间：2015年4月6日&mdash;&mdash;2015年5月15日</p>
<p>
	　　2.报名方式：有意者请填写《集美大学师资引进申报表》(人事处主页表格下载)，并通过电子邮件发送至集美大学招聘邮箱rmk@jmu.edu.cn(邮件主题请按如下格式：高校人才网-姓名-应聘鳗鲡现代产业技术教育部工程研究中心)，逾期不予受理。</p>
<p>
	　　3.报考人员联系电话应准确无误，并确保招聘期间保持通畅。</p>
<p>
	　　4.资格审查：报考人员应严格按照招聘岗位的条件要求报名，并对提交材料的真实性负责。凡个人填报信息不实，一经核实，即取消考核或聘用资格。</p>
<p>
	　　5.考核：具体事项和时间安排请关注集美大学人事处网站(网址：http://rsc.jmu.edu.cn/)。</p>
<p>
	<strong>　　五、联系方式</strong></p>
<p>
	　　联系地址：厦门市集美大学人事处(尚大楼1503)</p>
<p>
	　　邮编：361021</p>
<p>
	　　电话：0592-6181079</p>
<p>
	　　传真：0592-6181997</p>
<p>
	　　E-mail：rmk@jmu.edu.cn</p>
<p style="text-align: right;">
	　　集美大学人事处</p>
<p style="text-align: right;">
	　　2015年4月6日</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
