{dede:field name='keywords'}江西,事业单位招聘{/dede:field}
{dede:field name='description'}2015年江西科技师范大学招聘硕士人才公告{/dede:field}
{dede:field name='title'}2015年江西科技师范大学招聘硕士人才公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　江西备考交流QQ群：186502481<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/jiangxi/sy" target="_blank"><span style="color: #0000ff">2015年江西省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年江西科技师范大学招聘硕士人才公告</h2>
<strong>　　一、招聘单位简介</strong><br />
　　江西科技师范大学坐落于具有&quot;物华天宝、人杰地灵&quot;盛誉的历史文化名城--南昌，是我国首批建立的高等职业技术师范院校，是教育部重点建设的培养职业教育师资的高等院校，也是江西省唯一一所培养职业教育师资的多科性本科院校，主要培养职教师资、普教师资和应用型专门人才。经过61年的建设与发展，学校形成了以本科、研究生教育为主体，统筹发展继续教育的多学科、多层次的办学格局。2008年，学校以&quot;优秀&quot;成绩通过教育部本科教学工作水平评估。<br />
　　学校是硕士学位授予单位，现有7个一级学科硕士学位授权点(教育学、工商管理、化学、艺术学理论、音乐与舞蹈学、美术学、设计学)，40多个二级学科硕士学位授权点，3个硕士专业学位授权点(教育硕士、旅游管理硕士、艺术硕士)。建有省级重点一级学科3个(其中，高水平学科1个，覆盖20多个二级学科)、71个本科专业(其中，国家级特色专业2个&mdash;&mdash;应用化学、旅游管理，省级特色及品牌专业18个)、省级教学团队4个;建有博士后科研工作站1个，农业部国家研发中心1个，省级重点实验室4个、省级人文社会科学重点研究基地2个、省级实验教学示范中心3个、省级研究生教育创新基地3个、省高校工程技术研究中心2个、南昌市重点实验室7个、南昌市科研示范基地1个。<br />
　　学校现有专任教师1374人，其中，副高级以上专业技术职务人员549人(其中教授157人),具有博士、硕士学位教师941人、硕士生导师321人。教师队伍中，享受国务院和省政府特殊津贴专家19人，&ldquo;新世纪百千万人才工程&rdquo;国家级人选1人，教育部&quot;新世纪优秀人才支持计划&quot;2人，江西省井冈学者特聘教授1人，二级教授10人，&quot;江西省高校哲学社会科学领军人才&quot;1人，&quot;江西省主要学科学术和技术带头人&quot;3人，&ldquo;江西省新世纪百千万人才工程&rdquo;15人，&quot;赣鄱英才555工程&quot;12人，&quot;江西省青年科学家(井冈之星)9人，&ldquo;全国优秀教师&rdquo;1人，&quot;江西省教学名师&quot;8人，&ldquo;江西省模范教师&rdquo;1人，&quot;江西省中青年学科带头人&quot;34人，&quot;江西省高校中青年骨干教师&quot;74人。<br />
　　学校以&quot;明德精业&quot;为校训，建校以来，共培养了11万余名毕业生，为江西经济社会发展作出了积极贡献。近年来，毕业生就业率位居全省高校前列。近五年来，研究生及大学生在全国青少年科技创新、全国大学生英语、全国大学生广告艺术、全国大学生数学建模、电子设计、力学以及艺术设计、音乐、体育等各类竞赛和科技文化活动中，获省级以上奖项1293余项。学校健美操队队员代表国家队夺得了我国健美操项目的首枚世界金牌，学校被国家体育总局授予&quot;特别贡献奖&quot;。<br />
　　近五年来，学校承担了科技部、教育部、国家自然科学基金、国家社会科学基金、国家软科学项目以及全国教育科学规划重点项目等国家级、省部级科研项目735项;到位科研经费累计达13862.14万元;获得国家和省部级奖项27项;发表学术论文4098篇，其中SCI、EI、ISTP索引论文1267篇;出版专著72部;获发明专利54项。学校出版发行《职教论坛》、《江西科技师范大学学报》、《地方文化研究》3种学术刊物，《职教论坛》被评为全国中文核心期刊、获全国优秀职教期刊一等奖，文章转载率在全国职教类期刊中排名第一、在全国教育类期刊中排名第三，是我国最具影响力的职教刊物之一。<br />
<strong>　　二、招聘岗位、条件、人数</strong><br />
<table border="1" cellpadding="0" cellspacing="0" style="width:100%;" width="100%">
	<tbody>
		<tr>
			<td style="width:5.18%;">
				序号</td>
			<td style="width:13.1%;">
				部门</td>
			<td style="width:12.94%;">
				招聘<br />
				岗位</td>
			<td style="width:7.16%;">
				招聘人数</td>
			<td style="width:61.64%;">
				岗位条件</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				1</td>
			<td style="width:13.1%;">
				外国语学院</td>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				西班牙语语言文学专业，本科为西班牙语专业，获西班牙语专业四级证书，28周岁及以下（1987年1月1日后出生）</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				2</td>
			<td style="width:13.1%;">
				商学院</td>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				国际贸易学</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				3</td>
			<td style="width:13.1%;">
				教育学院</td>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				音乐学专业（音乐教育方向）</td>
		</tr>
		<tr>
			<td rowspan="3" style="width:5.18%;">
				4</td>
			<td rowspan="3" style="width:13.1%;">
				艺术设计学院</td>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				设计学类专业（服装设计方向）</td>
		</tr>
		<tr>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				设计学类专业（视觉传达方向）</td>
		</tr>
		<tr>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				美术学类专业</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:5.18%;">
				5</td>
			<td rowspan="2" style="width:13.1%;">
				体育学院</td>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				体育学类专业且获国家武士一级及以上运动等级资格（武术套路方向）</td>
		</tr>
		<tr>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				体育学类专业且获国家一级及以上运动等级资格（乒乓球方向）</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				6</td>
			<td style="width:13.1%;">
				旅游学院</td>
			<td style="width:12.94%;">
				教学岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				旅游管理类专业（旅游管理、酒店管理方向）</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:5.18%;">
				&nbsp;<br />
				7</td>
			<td rowspan="2" style="width:13.1%;">
				地方文化研究所</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				传播学专业（文化传播方向）</td>
		</tr>
		<tr>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				经济学类专业</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				8</td>
			<td style="width:13.1%;">
				宣传部</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				艺术学理论专业（艺术美学方向）</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				9</td>
			<td style="width:13.1%;">
				学工处</td>
			<td style="width:12.94%;">
				辅导员</td>
			<td style="width:7.16%;">
				8</td>
			<td style="width:61.64%;">
				专业不限</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				10</td>
			<td style="width:13.1%;">
				学科建设办公室</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				专业不限</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				11</td>
			<td style="width:13.1%;">
				科研处</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				专业不限</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				12</td>
			<td style="width:13.1%;">
				招就处</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				专业不限</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				13</td>
			<td style="width:13.1%;">
				财务处</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				会计专业</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				14</td>
			<td style="width:13.1%;">
				招标工作办公室</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				土木工程专业</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:5.18%;">
				15</td>
			<td rowspan="2" style="width:13.1%;">
				图书馆</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				图书馆学专业</td>
		</tr>
		<tr>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				计算机应用技术专业</td>
		</tr>
		<tr>
			<td style="width:5.18%;">
				16</td>
			<td style="width:13.1%;">
				法制办</td>
			<td style="width:12.94%;">
				管理岗</td>
			<td style="width:7.16%;">
				1</td>
			<td style="width:61.64%;">
				法学专业</td>
		</tr>
	</tbody>
</table>
　　注：
</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
