{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江台州市体育彩票管理中心招聘3人公告{/dede:field}
{dede:field name='title'}2015年浙江台州市体育彩票管理中心招聘3人公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江台州市体育彩票管理中心招聘3人公告</h2>
　　台州市体育彩票管理中心隶属于台州市体育局，自收自支事业单位性质，是中国体育彩票在台州的管理职能部门。因体育彩票事业发展需要，特招聘劳动合同用工(编制外)中心工作人员1名，体育彩票专管员2名。<br />
<strong>　　一、招聘原则与方式</strong><br />
　　坚持公平、公开、择优的原则。<br />
　　采用公开报名、统一考核、择优录取的方式。<br />
<strong>　　二、工作区域与人数</strong><br />
　　中心工作人员1人，路桥体彩站1人，玉环体彩站1人。<br />
<strong>　　三、工作岗位内容</strong><br />
　　(一)中心技术科工作人员<br />
　　1、负责中心官网、中心信息系统的应用管理;<br />
　　2、负责体彩终端设备的技术规范和使用管理;<br />
　　3、负责技术相关的服务管理、档案管理、培训及安全管理;<br />
　　(二)体育彩票专管员<br />
　　1.负责区域内体育彩票销售点的日常管理服务工作;<br />
　　2、负责销售点的日常巡查、资料配送、宣传培训等服务工作，确保销售点正常有序的销售;<br />
　　3、负责监督销售点形象，以及销售点违规处理等工作，保持销售点形象达标、行为规范;<br />
　　4、负责销售点终端的正常维护及保养，保障销售点正常售票;<br />
　　5、完成市中心、当地体育局交办的其他事务。<br />
<strong>　　四、招聘条件</strong><br />
　　1、1985年1月1日出生，男女不限，台州户籍，本科以上学历，身体健康，有较好的口头表达、沟通能力;<br />
　　2、热爱体彩工作，有责任心、遵纪守法，具备吃苦耐劳、爱岗敬业、较强的团队合作精神，无不良记录;<br />
　　3、有体育彩票销售经历，爱好体育并熟悉足球、篮球赛事，以及具有市场营销等工作经验者优先。<br />
　　<strong>五、待遇</strong><br />
　　实习期满后，工资由基本工资、考勤奖、补贴组成，缴五险一金。<br />
　<strong>　六、报名方法</strong><br />
　　1、现场报名：地点台州市体育彩票管理中心办公室(椒江经中路322号)，0576-88836825，联系人杨先生。<br />
　　2、网上报名：填写报名表及相关资料电子稿发至报名邮箱yangjin_006@163.com<br />
　　3、截止时间：2015年4月25日<br />
　　4、所需资料：报名表、个人简历、本人身份证、毕业证书、其他相关证件原件及复印件;<br />
　　台州市体育彩票管理中心专管员报名表<br />
　　报考区域： 填表时间：　　年　月　日<br />
<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width:79px;height:38px;">
				姓&nbsp;&nbsp;名</td>
			<td style="width:35px;height:38px;">
				&nbsp;</td>
			<td style="width:32px;height:38px;">
				身份证号</td>
			<td style="width:31px;height:38px;">
				&nbsp;</td>
			<td style="width:31px;height:38px;">
				&nbsp;</td>
			<td style="width:31px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td colspan="3" style="width:19px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td colspan="2" style="width:18px;height:38px;">
				&nbsp;</td>
			<td colspan="2" style="width:18px;height:38px;">
				&nbsp;</td>
			<td colspan="2" style="width:18px;height:38px;">
				&nbsp;</td>
			<td colspan="2" style="width:18px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td style="width:18px;height:38px;">
				&nbsp;</td>
			<td rowspan="3" style="width:52px;height:38px;">
				（照片）</td>
		</tr>
		<tr>
			<td style="width:79px;height:41px;">
				户口<br />
				所在地</td>
			<td style="width:35px;height:41px;">
				&nbsp;</td>
			<td style="width:32px;height:41px;">
				民族</td>
			<td colspan="3" style="width:92px;height:41px;">
				&nbsp;</td>
			<td colspan="2" style="width:36px;height:41px;">
				性别</td>
			<td colspan="6" style="width:65px;height:41px;">
				&nbsp;</td>
			<td colspan="6" style="width:57px;height:41px;">
				政治<br />
				面貌</td>
			<td colspan="7" style="width:115px;height:41px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:79px;height:32px;">
				毕业<br />
				院校</td>
			<td colspan="5" style="width:159px;height:32px;">
				&nbsp;</td>
			<td colspan="5" style="width:69px;height:32px;">
				是否全日制</td>
			<td colspan="3" style="width:32px;height:32px;">
				&nbsp;</td>
			<td colspan="6" style="width:57px;height:32px;">
				毕业<br />
				时间</td>
			<td colspan="7" style="width:115px;height:32px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:79px;height:39px;">
				所学<br />
				专业</td>
			<td colspan="10" style="width:228px;height:39px;">
				&nbsp;</td>
			<td colspan="5" style="width:51px;height:39px;">
				学历</td>
			<td colspan="8" style="width:98px;height:39px;">
				&nbsp;</td>
			<td colspan="3" style="width:54px;height:39px;">
				&nbsp;学位</td>
			<td style="width:52px;height:39px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:79px;height:34px;">
				家庭住址</td>
			<td colspan="9" style="width:225px;height:34px;">
				&nbsp;</td>
			<td colspan="8" style="width:70px;height:34px;">
				联系电话、手机</td>
			<td colspan="10" style="width:189px;height:34px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:79px;height:179px;">
				<strong>教育经历</strong></td>
			<td colspan="27" style="width:483px;height:179px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:79px;height:194px;">
				<strong>工作经历</strong></td>
			<td colspan="27" style="width:483px;height:194px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="28" style="width:562px;height:92px;">
				<strong>本人声明：上述填写内容真实完整。如有不实，本人愿承担取消招聘资格的责任。</strong><br />
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>申请人（签名）：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;年&nbsp;&nbsp;&nbsp;月&nbsp;&nbsp;&nbsp;日</strong></td>
		</tr>
		<tr>
			<td style="width:79px;">
				&nbsp;</td>
			<td style="width:35px;">
				&nbsp;</td>
			<td style="width:32px;">
				&nbsp;</td>
			<td style="width:31px;">
				&nbsp;</td>
			<td style="width:31px;">
				&nbsp;</td>
			<td style="width:31px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:12px;">
				&nbsp;</td>
			<td style="width:3px;">
				&nbsp;</td>
			<td style="width:4px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:10px;">
				&nbsp;</td>
			<td style="width:9px;">
				&nbsp;</td>
			<td style="width:11px;">
				&nbsp;</td>
			<td style="width:7px;">
				&nbsp;</td>
			<td style="width:9px;">
				&nbsp;</td>
			<td style="width:10px;">
				&nbsp;</td>
			<td style="width:12px;">
				&nbsp;</td>
			<td style="width:6px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:18px;">
				&nbsp;</td>
			<td style="width:52px;">
				&nbsp;</td>
		</tr>
	</tbody>
</table>
　　注：1、本表内容必须须如实填写，如有虚假，后果自负。<br />
　　2、笔试、面试及有关事项另行通知。
<div style="text-align: right;">
	　　台州市体育彩票管理中心<br />
	　　2015年4月9日</div>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
