{dede:field name='keywords'}江西,事业单位招聘{/dede:field}
{dede:field name='description'}2015年江西广丰县公开招聘事业单位工作人员20人公告{/dede:field}
{dede:field name='title'}2015年江西广丰县公开招聘事业单位工作人员20人公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　江西备考交流QQ群：186502481<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/jiangxi/sy" target="_blank"><span style="color: #0000ff">2015年江西省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	<strong>2015年江西广丰县公开招聘事业单位工作人员20人公告</strong></h2>
<p>
	　　为进一步深化我县事业单位人事制度改革，建立科学、规范、公正的选人用人机制，切实加强我县事业单位人才队伍建设，经县委、县政府研究，决定面向社会公开招聘事业单位工作人员20名，现将有关事项公告如下：</p>
<p>
	　<strong>　一、招聘岗位、人数及条件</strong></p>
<p>
	　　见附件：《广丰县2015年事业单位公开招聘岗位一览表》</p>
<p>
	　<strong>　二、报名时间及方式</strong></p>
<p>
	　　1、网上报名时间：2015年4月27日9:00-4月30日16:00。</p>
<p>
	　　2、报名方式：应聘人员登录上饶市人力资源和社会保障网(www.srrcw.com)进行网上报名。具体步骤按《上饶市事业单位2015年公开招聘工作实施方案》(以下简称《方案》)的规定操作。</p>
<p>
	<strong>　　三、笔试、资格审查及面试</strong></p>
<p>
	　　考试采取笔试与面试相结合的方法进行。岗位信息表备注栏另有规定的，按其规定执行。</p>
<p>
	　　1、笔试。岗位报名人数与招聘计划比例须达到3:1方可开考。完成网上注册、缴费的应聘人员于2015年5月17日参加上饶市事业单位公开招聘公共科目和专业科目的考试。具体安排见笔试准考证。</p>
<p>
	　　2、面试。需笔试的岗位，根据笔试成绩按岗位招聘人数2:1的比例确定入闱面试人员。面试工作按照《方案》具体规定进行。</p>
<p>
	　　3、资格审查。面试前，入闱面试人员应按照《方案》的规定，在规定的时间内携带相关证件(证明)、照片等参加资格审查。资格审查工作由广丰县人力资源和社会保障局会同招聘单位及其主管部门负责，具体时间和地点，另行通知。面试人员的递补按《方案》执行。</p>
<p>
	<strong>　　四、体检和考核</strong></p>
<p>
	　　1、根据总成绩按招聘岗位从高分到低分等额确定体检、考核对象。</p>
<p>
	　　2、体检由市人力资源和社会保障局统一组织，参照公务员录用体检规定执行。考核工作由广丰县人力资源和社会保障局会同招聘单位及其主管部门负责。</p>
<p>
	<strong>　　五、公示和聘用</strong></p>
<p>
	　　对经体检、考核合格的拟聘人员进行公示，公示期为7个工作日。公示无异议的，办理相关聘用手续。聘用人员享受事业单位工作人员工资福利待遇。</p>
<p>
	<strong>　　六、其他未尽事宜，按照《方案》有关规定执行。</strong></p>
<p>
	　　本公告由广丰县人力资源和社会保障局负责解释。</p>
<p>
	　　联系电话：0793&mdash;2635505(广丰县人力资源和社会保障局)</p>
<p>
	<strong><a href="http://www.srrcw.com/UploadFiles/2015-04/macil/003%E5%B9%BF%E4%B8%B0%E5%8E%BF2015%E5%B9%B4%E4%BA%8B%E4%B8%9A%E5%8D%95%E4%BD%8D%E5%85%AC%E5%BC%80%E6%8B%9B%E8%81%98%E8%AE%A1%E5%88%92%E7%94%B3%E6%8A%A5%E6%B1%87%E6%80%BB%E8%A1%A8.xls">　　附件：《广丰县2015年事业单位招聘工作人员岗位一览表》</a></strong></p>
<p style="text-align: right;">
	　　广丰县人力资源和社会保障局</p>
<p style="text-align: right;">
	　　2015年4月10日</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
