{dede:noteinfo notename="砍柴网" channelid="1" macthtype="string"
refurl="" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.ikanchai.com/biz/business/(*).shtml"
startid="1" endid="5" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="main newslist">{/dede:areastart}
    {dede:areaend}<div class="page">{/dede:areaend}
{/dede:listrule}
