{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江嘉兴外国语学校教师招聘人员公告{/dede:field}
{dede:field name='title'}2015年浙江嘉兴外国语学校教师招聘人员公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江嘉兴外国语学校教师招聘人员公告</h2>
<p>
	　　嘉兴外国语学校是经嘉兴市教育局批准成立的一所以外语教学为特色的全日制民办完全中学，也是2004年嘉兴市政府接轨上海的教育合作项目。学校位于嘉兴中环南路，学校坚持&ldquo;文理并重，全面发展，注重特长，接轨国际文化&rdquo;的办学宗旨，在全面提高学生文化素质的前提下，以突出外语教学为特色。根据学校发展需要，面向嘉兴大市公开招聘教师，现将有关事项公告如下：</p>
<p>
	　<strong>　一、招聘岗位、人数及对象：</strong></p>
<p>
	　　高中教师：数学1名;英语1名;历史1名;通用1名;信息技术1名;</p>
<p>
	<strong>　　二、应聘条件</strong></p>
<p>
	　　全日制师范类普通高校应届毕业生和在职学校教师。其中信息技术要求会使用Flash，Photoshop，VB程序设计以及数据库等知识软件，ado技术调用数据库。</p>
<p>
	　<strong>　三、应聘办法及时间</strong></p>
<p>
	　　应聘者请将学历证书、职称证书、身份证、教师资格证、各类获奖证书、教学业绩等相关证明材料复印件及个人学习工作简历(注：推荐材料恕不退还)由本人到学校或通过各种形式投递至嘉兴外国语学校校务办公室报名。初审合格者，电话通知。(具体考核事宜另行通知)</p>
<p>
	　　应聘日期：即日起至2015年4月19日</p>
<p>
	　　电话：0573-82626615，82626553;地址：嘉兴市中环南路8183号;</p>
<p>
	　　联系人：朱老师(13757369776)、石老师(15068346761)</p>
<p>
	　　祖老师(13484180537)、莫老师(13605731981)</p>
<p>
	　　邮编：314001</p>
<p>
	　　学校网址：http://www.jflsedu.com/</p>
<p style="text-align: right;">
	　　嘉兴外国语学校</p>
<p style="text-align: right;">
	　　2015年4月8日</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
