{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建福州鼓楼区博物馆招聘讲解员公告{/dede:field}
{dede:field name='title'}2015年福建福州鼓楼区博物馆招聘讲解员公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建福州鼓楼区博物馆招聘讲解员公告</h2>
<p>
	　　因工作需要，我局面向社会公开招聘若干名讲解接待员，从事鼓楼区博物馆讲解、接待工作，待遇从优。</p>
<p>
	　　<strong>一、招聘条件</strong></p>
<p>
	　　1、性别：女</p>
<p>
	　　2、年龄：25周岁以下</p>
<p>
	　　3、学历：大专以上</p>
<p>
	　　4、身高： 165cm左右</p>
<p>
	　　5、其他：普通话二(甲)含以上，形象好，气质佳，擅长弹奏古筝、琵琶等乐器者优先。</p>
<p>
	　　<strong>二、报名方式</strong></p>
<p>
	　　1、有意应聘者，请将个人简历、照片于2015年4月24日前发送电子邮件至2898001056 @qq.com</p>
<p>
	　　2、我局审核后将电话通知面试时间、地点。</p>
<p>
	　　报名者应对提供的全部资料的真实性负责，经查如属伪造的，将取消应聘资格。</p>
<p>
	　　联系电话：87881275</p>
<p style="text-align: right;">
	　　鼓楼区文体局</p>
<p style="text-align: right;">
	　　2015年4月3日</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
