{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建厦门翔安区统计局职业见习生招聘公告{/dede:field}
{dede:field name='title'}2015年福建厦门翔安区统计局职业见习生招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建厦门翔安区统计局职业见习生招聘公告</h2>
<p>
	　　因工作需要，决定面向社会提供翔安区统计局职业见习岗位2个，现将有关事项公布如下：</p>
<p>
	　　<strong>一、人员性质</strong></p>
<p>
	　　本次招聘的毕业生职业见习人员在区统计局从事统计调查等相关辅助工作,见习时间为期一年。</p>
<p>
	<strong>　　二、基本条件</strong></p>
<p>
	　　1、普通高等、中等院校待就业的毕业生;</p>
<p>
	　　2、入校前具有厦门市同安区或翔安区常住户口;</p>
<p>
	　　3、有对见习人员负监督管理和经济责任的担保人进行担保;</p>
<p>
	　　4、自愿提出见习申请。</p>
<p>
	　<strong>　三、招聘岗位、人数及报名条件</strong></p>
<p>
	　　见习统计局统计调查岗位：2人，男女不限，大专及以上学历。</p>
<p>
	<strong>　　四、报名有关事项</strong></p>
<p>
	　　报名时间：2015年4月7日&mdash;2015年6月30日(上班时间)</p>
<p>
	　　报名地点：翔安区政府大院4号楼106#</p>
<p>
	　　咨询电话：7889393</p>
<p>
	　　报名表见附件：报名表请应聘人员自行下载填写打印。报名时应提交报名表一式一份，近期1寸免冠同版相片1张(贴于报名表上相应位置)，并提供以下材料的原件及复印件：身份证、户口薄、学历证、报到证。</p>
<p style="text-align: right;">
	　　翔安区统计局</p>
<p style="text-align: right;">
	　　2015年4月7日</p>
<p>
	　　附 件 下 载:</p>
<p>
	<strong>　　&middot;附：<a href="http://rlj.xiangan.gov.cn/gzdt/gsgg/201504/P020150407613002813912.doc">2015年厦门翔安区职业见习人员招聘报名表.doc</a></strong></p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
