{dede:field name='keywords'}江西,事业单位招聘{/dede:field}
{dede:field name='description'}2015年江西省科学院能源研究所招聘工作人员公告{/dede:field}
{dede:field name='title'}2015年江西省科学院能源研究所招聘工作人员公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　江西备考交流QQ群：186502481<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/jiangxi/sy" target="_blank"><span style="color: #0000ff">2015年江西省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年江西省科学院能源研究所招聘工作人员公告</h2>
<p>
	　<strong>　一、招聘单位简介</strong></p>
<p>
	　　江西省科学院能源研究所隶属于江西省科学院，是江西省唯一专业从事能源与环保技术研究与开发的省级科研机构。主要从事能源战略与低碳经济、新能源与可再生能源、节能环保新技术与新产品、水污染控制与资源利用、计算机信息技术等领域研究和开发工作，并开展相关节能减排技术服务。</p>
<p>
	　<strong>　二、招聘岗位、条件</strong></p>
<table border="1" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td width="133">
				<p align="center">
					<span>招聘岗位</span></p>
			</td>
			<td width="108">
				<p align="center">
					<span>招聘人数</span></p>
			</td>
			<td width="252">
				<p align="center">
					<span>岗位条件</span></p>
			</td>
		</tr>
		<tr>
			<td width="133">
				<p align="center">
					<span>能源技术研究</span></p>
			</td>
			<td width="108">
				<p align="center">
					<span>2</span></p>
			</td>
			<td width="252">
				<p>
					<span>能源动力类专业。第一学历为统招本科并获得学士学位，全日制统招博士研究生学历学位，海外留学人员需教育部学历学位认证及留学回国人员证明。年龄不超过<span>35</span>周岁，博士后及海外留学回国人才年龄不超过<span>40</span>周岁，身体健康，品行端正。</span></p>
			</td>
		</tr>
		<tr>
			<td width="133">
				<p align="center">
					<span>环保技术研究</span></p>
			</td>
			<td width="108">
				<p align="center">
					<span>2</span></p>
			</td>
			<td width="252">
				<p>
					<span>环境科学类专业。第一学历为统招本科并获得学士学位，全日制统招博士研究生学历学位，海外留学人员需教育部学历学位认证及留学回国人员证明。年龄不超过<span>35</span>周岁，博士后及海外留学回国人才年龄不超过<span>40</span>周岁，身体健康，品行端正。</span></p>
			</td>
		</tr>
		<tr>
			<td width="133">
				<p align="center">
					<span>计算机技术研究</span></p>
			</td>
			<td width="108">
				<p align="center">
					<span>1</span></p>
			</td>
			<td width="252">
				<p>
					<span>计算机科学与技术类专业。第一学历为统招本科并获得学士学位，全日制统招博士研究生学历学位，海外留学人员需教育部学历学位认证及留学回国人员证明。年龄不超过<span>35</span>周岁，博士后及海外留学回国人才年龄不超过<span>40</span>周岁，身体健康，品行端正。</span></p>
			</td>
		</tr>
	</tbody>
</table>
<p>
	<strong>　　三、报名办法</strong></p>
<p>
	　　1、报名时间：2015年3月10日至12月31日岗位招满为止。</p>
<p>
	　　2、报名地点：江西省科学院能源研究所(南昌市昌东大道7777号，江西省科学院创新大楼508室)。</p>
<p>
	　　3、联系电话：0791-88175782 邮箱：xys1985@163.com</p>
<p>
	　　4、报名需携带的材料：身份证、毕业证、 学位证原件及复印件，近期免冠照片3张。有工作单位的还需要携带有现工作单位出具的同意报考证明。</p>
<p>
	　<strong>　四、考核的方式</strong></p>
<p>
	　　1、考核方式：采取直接面试考核择优录取的方式进行招聘，面试内容为相关专业知识及实践操作。</p>
<p>
	　　2、面试时间、地点：时间另行通知，地点在江西省科学院能源研究所(南昌市昌东大道7777号，江西省科学院创新大楼501室)</p>
<p>
	<strong>　　五、体检</strong></p>
<p>
	　　1、根据考核成绩从高分到低分，按岗位招聘人数1:1的比例择优确定体检人员。</p>
<p>
	　　2、在我单位指定的卫生机构体检，体检标准参照公务员标准执行。</p>
<p>
	<strong>　　六、聘用</strong></p>
<p>
	　　经考核、体检合格，公示无异议后办理相关聘用手续。试用期为三个月，合格后办理正式调入手续</p>
<p>
	<strong>　　七、待遇</strong></p>
<p>
	　　1、享受国家规定的工资福利待遇。</p>
<p>
	　　2、录用人员均为全额拨款事业编制，工资不低于专业技术八级待遇。</p>
<p>
	　　3、提供科研启动资金20万元。每月发放1000元博士津贴，提供安家费10万元，一年期过渡性住房一间。</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
