{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建中药大学附属福州中医院招聘产科医师的公告{/dede:field}
{dede:field name='title'}2015年福建中药大学附属福州中医院招聘产科医师的公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建中药大学附属福州中医院招聘产科医师的公告</h2>
<p>
	　　我院系三级甲等综合性中医医院，根据医院发展需要，现急需招聘一名产科医师，详细信息如下：</p>
<center>
	<img alt="福州招聘" border="1" height="88" src="/uploads/allimg/c150412/142W9632cCF-1GO.png" width="679" /></center>
<p>
	<strong>　　一、报名方式：</strong></p>
<p>
	　　发送个人详细简历到fzzyyrsk@163.com邮箱，邮件标题格式为&ldquo;姓名+应聘岗位&rdquo;。</p>
<p>
	<strong>　　二、考试时间：</strong></p>
<p>
	　　根据报名数确定考试时间，将以电话形式通知应聘人员。</p>
<p>
	<strong>　　三、招聘方式：</strong></p>
<p>
	　　采取面试方式进行招聘，面试由我院院领导及相关科室专家成员组成，面试内容为综合能力测试。成绩择优录取。</p>
<p>
	　　<strong>四、体检：</strong></p>
<p>
	　　面试合格者，我院将统一组织体检，具体事项我院将以电话通知应聘人员。</p>
<p>
	　<strong>　五、其他事项</strong></p>
<p>
	　　地址：福州市鼓东路102号</p>
<p>
	　　医院官网：http://www.fzszyy.cn/</p>
<p>
	　　联系电话：0591-87678565</p>
<p>
	　　联系人：小吕</p>
<p>
	　　邮箱：fzzyyrsk@163.com</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150412/142W9632cCF-1GO_lit.png{/dede:field}
