<li><img src="http://img.ikanchai.com/templates/ikanchai/html/images/symbol-1.png" alt="[field:title /]"><a href="[field:arcurl /]" target="_blank" title="[field:title /]">[field:title /]</a>
	  		   	<img src="http://img.ikanchai.com/templates/ikanchai/html/images/symbol-1.png" alt="[field:title /]"><a href="[field:arcurl /]" target="_blank" title="[field:title /]">[field:title /]</a>
	  		   
	  </li>