{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建中医药大学招聘公告{/dede:field}
{dede:field name='title'}2015年福建中医药大学招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建中医药大学招聘公告</h2>
　　福建中医药大学是福建省重点建设高校。因工作需要，我校拟向社会公开招聘工作人员11名。根据《福建省省属事业单位公开招聘工作人员考试暂行办法》的规定，制定具体方案如下：<br />
<strong>　　一、基本条件</strong><br />
　　1.具有中华人民共和国国籍，拥护中国共产党的领导，热爱社会主义，遵纪守法，品行端正;<br />
　　2.身体健康，符合公务员录用体检标准;<br />
　　3.151005岗位报名者应为2013、2014、2015届毕业生，取得境外学历学位报考者届别认定时间以取得教育部学历学位认证书年份为准;<br />
　　151006岗位报考者年龄应在30周岁及以下(1984年4月3日以后出生)，其余岗位报考者年龄应在40周岁及以下(1974年4月3日以后出生);<br />
　　4.报考者应取得岗位要求的相应学历、学位;<br />
　　5.各项资格认定截止时间为2015年7月31日;取得境外学历学位证书报考者应提供教育部留学服务中心出具的学历学位认证书(认证书截止时间为2015年7月31日);<br />
　　6.151006岗位报考者应为中共党员;<br />
　　7. 151007岗位报考者应具有相关专业初级及以上专业技术职称。<br />
<strong>　　二、招聘岗位及要求</strong><br />
<table border="0" cellpadding="0" cellspacing="0" style="width:565px;" width="565">
	<tbody>
		<tr>
			<td style="width:85px;height:54px;">
				<strong>岗位代码</strong></td>
			<td style="width:132px;height:54px;">
				<strong>岗位名称</strong></td>
			<td style="width:48px;height:54px;">
				<strong>招聘人数</strong></td>
			<td style="width:144px;height:54px;">
				<strong>专业</strong></td>
			<td style="width:156px;height:54px;">
				<strong>学历学位</strong></td>
		</tr>
		<tr>
			<td style="width:85px;height:110px;">
				151001</td>
			<td style="width:132px;height:110px;">
				教师1</td>
			<td style="width:48px;height:110px;">
				1</td>
			<td style="width:144px;height:110px;">
				中医学类</td>
			<td style="width:156px;height:110px;">
				全日制普通高等院校研究生学历、硕士及以上学位</td>
		</tr>
		<tr>
			<td style="width:85px;height:76px;">
				151002</td>
			<td style="width:132px;height:76px;">
				教师2</td>
			<td style="width:48px;height:76px;">
				1</td>
			<td style="width:144px;height:76px;">
				护理学类</td>
			<td style="width:156px;height:76px;">
				全日制普通高等院校研究生学历、<br />
				硕士及以上学位</td>
		</tr>
		<tr>
			<td style="width:85px;height:76px;">
				151003</td>
			<td style="width:132px;height:76px;">
				教师3</td>
			<td style="width:48px;height:76px;">
				1</td>
			<td style="width:144px;height:76px;">
				药学类、<br />
				生物科学类</td>
			<td style="width:156px;height:76px;">
				全日制普通高等院校研究生学历、<br />
				硕士及以上学位</td>
		</tr>
		<tr>
			<td style="width:85px;height:90px;">
				151004</td>
			<td style="width:132px;height:90px;">
				教师5</td>
			<td style="width:48px;height:90px;">
				1</td>
			<td style="width:144px;height:90px;">
				政治学类</td>
			<td style="width:156px;height:90px;">
				全日制普通高等院校研究生学历、<br />
				硕士及以上学位</td>
		</tr>
		<tr>
			<td style="width:85px;height:104px;">
				151005</td>
			<td style="width:132px;height:104px;">
				教师4</td>
			<td style="width:48px;height:104px;">
				1</td>
			<td style="width:144px;height:104px;">
				法学类</td>
			<td style="width:156px;height:104px;">
				全日制普通高等院校研究生学历、<br />
				硕士及以上学位</td>
		</tr>
		<tr>
			<td style="width:85px;height:91px;">
				151006</td>
			<td style="width:132px;height:91px;">
				辅导员</td>
			<td style="width:48px;height:91px;">
				5</td>
			<td style="width:144px;height:91px;">
				不限</td>
			<td style="width:156px;height:91px;">
				全日制普通高等院校研究生学历、<br />
				硕士及以上学位</td>
		</tr>
		<tr>
			<td style="width:85px;height:61px;">
				151007</td>
			<td style="width:132px;height:61px;">
				现场施工管理人员</td>
			<td style="width:48px;height:61px;">
				1</td>
			<td style="width:144px;height:61px;">
				土木工程、结构工程、建筑工程施工与管理</td>
			<td style="width:156px;height:61px;">
				全日制普通高等院校本科及以上学历、学士及以上学位</td>
		</tr>
	</tbody>
</table>
　　注：专业设置参照《福建省机关事业单位招考专业指导目录》(2015)，考生可登陆省人社厅门户网站(http://www.fjrs.gov.cn)查看。
</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
