{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建农林大学招聘辅导员公告{/dede:field}
{dede:field name='title'}2015年福建农林大学招聘辅导员公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建农林大学招聘辅导员公告</h2>
　　福建农林大学是福建省重点支持建设的三所高水平大学之一，是国家农业部、国家林业局与福建省政府共建大学。学校是福建省唯一的农林本科高校，在培养高层次、高质量人才、开展高水平科技创新和社会服务、推进对外开放等方面取得了丰硕的办学成果。现因工作需要，拟向社会公开招聘辅导员18名。根据《福建省省属事业单位公开招聘工作人员考试暂行办法》的规定，制定具体方案如下：<br />
<strong>　　一、基本条件</strong><br />
　　1.具有中华人民共和国国籍，拥护中国共产党的领导，热爱社会主义，遵纪守法，品行端正。<br />
　　2.身体健康，符合《福建省教师资格申请人员体检标准及办法》体检标准。<br />
　　3.全日制普通高等院校毕业、取得相应学历学位、符合毕业生派遣条件的研究生学历、硕士及以上学位毕业生(其中2015届毕业生应在2015年7月31日前取得相应学历学位)，且具备下列条件：<br />
　　(1)年龄要求：30周岁及以下(1984年4月3日及以后出生)。<br />
　　(2)政治面貌：中共党员(入党时间截止到2015年7月31日)。<br />
　　(3)学生干部经历要求：大学期间担任满一学年及以上主要学生干部职务(指校、院学生会或研究生会主席、副主席，校、院团委副书记或团总支书记，校、院团委或学生会或研究生会副部长及以上;校、院学生社团联合会主席、副主席，校、院学生自律委员会主任、副主任，校、院大学生艺术团团长、副团长;班长、团支部书记;学生党支部书记;校易班学生工作站站长、副站长、部长;校电台台长，校报记者团团长，校级团学组织主要刊物主编及以上职务)。上述学生干部职务任职时间截止到2015年7月31日。取得境外学历学位报考者学生干部经历不作要求。<br />
　　4.取得境外学历学位证书报名者应提供教育部留学服务中心出具的学历学位认证书(认证书截止时间为2015年7月31日)。<br />
<strong>　　二、招聘岗位及要求</strong><br />
<table border="1" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width:73px;height:57px;">
				岗位序号</td>
			<td style="width:117px;height:57px;">
				招聘岗位</td>
			<td style="width:48px;height:57px;">
				招聘<br />
				人数</td>
			<td style="width:51px;height:57px;">
				专业</td>
			<td style="width:125px;height:57px;">
				学历学位</td>
			<td style="width:72px;height:57px;">
				其他要求</td>
			<td style="width:139px;height:57px;">
				备注</td>
		</tr>
		<tr>
			<td style="width:73px;height:57px;">
				SF201501</td>
			<td style="width:117px;height:57px;">
				男生公寓<br />
				辅导员</td>
			<td style="width:48px;height:57px;">
				7</td>
			<td style="width:51px;height:57px;">
				不限</td>
			<td style="width:125px;height:57px;">
				研究生学历，<br />
				硕士及以上学位</td>
			<td style="width:72px;height:57px;">
				男性</td>
			<td style="width:139px;height:57px;">
				入住男生公寓</td>
		</tr>
		<tr>
			<td style="width:73px;height:76px;">
				SF201502</td>
			<td style="width:117px;height:76px;">
				安溪茶学院<br />
				男生公寓辅导员</td>
			<td style="width:48px;height:76px;">
				3</td>
			<td style="width:51px;height:76px;">
				不限</td>
			<td style="width:125px;height:76px;">
				研究生学历，<br />
				硕士及以上学位</td>
			<td style="width:72px;height:76px;">
				男性</td>
			<td style="width:139px;height:76px;">
				1、入住男生公寓<br />
				2、工作地点：安溪茶学院（泉州安溪）</td>
		</tr>
		<tr>
			<td style="width:73px;height:57px;">
				SF201503</td>
			<td style="width:117px;height:57px;">
				女生公寓<br />
				辅导员</td>
			<td style="width:48px;height:57px;">
				5</td>
			<td style="width:51px;height:57px;">
				不限</td>
			<td style="width:125px;height:57px;">
				研究生学历，<br />
				硕士及以上学位</td>
			<td style="width:72px;height:57px;">
				女性</td>
			<td style="width:139px;height:57px;">
				入住女生公寓</td>
		</tr>
		<tr>
			<td style="width:73px;height:78px;">
				SF201504</td>
			<td style="width:117px;height:78px;">
				安溪茶学院<br />
				女生公寓辅导员</td>
			<td style="width:48px;height:78px;">
				3</td>
			<td style="width:51px;height:78px;">
				不限</td>
			<td style="width:125px;height:78px;">
				研究生学历，<br />
				硕士及以上学位</td>
			<td style="width:72px;height:78px;">
				女性</td>
			<td style="width:139px;height:78px;">
				1、入住女生公寓<br />
				2、工作地点：安溪茶学院（泉州安溪）</td>
		</tr>
	</tbody>
</table>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
