{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江省宁波潘火派出所招聘指挥室接警员岗位人员公告{/dede:field}
{dede:field name='title'}2015年浙江省宁波潘火派出所招聘指挥室接警员岗位人员公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江省宁波潘火派出所招聘指挥室接警员岗位人员公告</h2>
<p>
	　　因工作需要，经研究决定面向社会公开招聘协辅警人员，从事指挥室接警员相关工作。现将有关事项公告如下：</p>
<p>
	　　<strong>一、招聘范围对象及条件</strong></p>
<p>
	　　(一)拥护党的路线、方针和政策，热爱公安工作;</p>
<p>
	　　(二)遵纪守法、作风正派，能够保守工作秘密，无违法犯罪前科;</p>
<p>
	　　(三)高中及以上学历;</p>
<p>
	　　(四)性别要求为女性;</p>
<p>
	　　(五)年龄在18周岁以上;</p>
<p>
	　　<strong>二、招聘程序与办法</strong></p>
<p>
	　　招聘工作贯彻公开、平等、竞争、择优原则，采取公开报名、统一面试、择优录用的办法进行。</p>
<p>
	　　(一)时间：即日起至2015年4月15日;</p>
<p>
	　　(二)地点：鄞州潘火派出所(鄞州区潘火街道金源路787号);</p>
<p>
	　　(三)办法：发送个人简历发送邮箱至2495470321@qq.com，邮件主题格式为&ldquo;姓名+简历&rdquo;，面试时间另行通知。</p>
<p>
	　<strong>　三、其他相关规定</strong></p>
<p>
	　　(一)有关招聘政策和具体要求及事项，请仔细阅读本公告，仅在规定的报名时间内进行，逾期一概不予受理。</p>
<p>
	　　(二)试用期满合格者正式办理聘用手续，与潘火街道签订劳务派遣合同，年薪3万5千元以上，交纳养老、医疗等五类社会保险，具体面谈。</p>
<p>
	　　(三)本公告由潘火派出所负责解释。</p>
<p>
	　　(四)联系人：余先生; 联系电话：18067592560 / 88154932</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
