{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建福州鼓楼区行政服务中心招聘公告{/dede:field}
{dede:field name='title'}2015年福建福州鼓楼区行政服务中心招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建福州鼓楼区行政服务中心招聘公告</h2>
<p>
	　　因工作需要，现面向社会公开招聘1名工作人员，有关事项如下：</p>
<p>
	<strong>　　一、招聘岗位</strong></p>
<p>
	　　咨询台导办员1名。</p>
<p>
	　<strong>　二、应聘条件</strong></p>
<p>
	　　1、遵纪守法，普通话标准，礼仪规范;</p>
<p>
	　　2、全日制大专以上学历;</p>
<p>
	　　3、女性，年龄30周岁以下，身体健康;</p>
<p>
	　　4、会讲福州话者优先。</p>
<p>
	<strong>　　三、报名时间和地点</strong></p>
<p>
	　　1、报名时间：2015年4月10日至4月30日(正常上班时间09：00&mdash;17：00);</p>
<p>
	　　2、报名地点：鼓楼区行政服务中心综合科(温泉公园路89号);</p>
<p>
	　　3、联系人：林女士,88085758。</p>
<p>
	<strong>　　四、其他事项</strong></p>
<p>
	　　1、报名时，需提供以下资料：简历、身份证、学历证书、学位证书原件和复印件，本人近期一寸免冠照片2张;</p>
<p>
	　　2、招聘人员经面试、笔试后择优录用，工资待遇按中心劳务派遣合同制人员标准，享受五险一金和年终绩效奖金。</p>
<p style="text-align: right;">
	　　鼓楼区行政服务中心</p>
<p style="text-align: right;">
	　　2015年4月9日</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
