{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建中医药大学附属单位公共岗位招聘公告{/dede:field}
{dede:field name='title'}2015年福建中医药大学附属单位公共岗位招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建中医药大学附属单位公共岗位招聘公告</h2>
　　福建中医药大学是福建省重点建设高校。因工作需要，我校所属4所直属附属单位拟向社会公开招聘工作人员10名(具体单位岗位要求附后)。根据《福建省省属事业单位公开招聘工作人员考试暂行办法》的规定，制定具体方案如下：<br />
<strong>　　一、基本条件</strong><br />
　　1.具有中华人民共和国国籍，拥护中国共产党的领导，热爱社会主义，遵纪守法，品行端正;<br />
　　2.身体健康，符合公务员录用体检标准;<br />
　　3.年龄40周岁及以下(1974年4月3日及以后出生);<br />
　　4.报考者应取得岗位要求的相应学历、学位;<br />
　　5.各项资格认定截止时间为2015年7月31日;取得境外学历学位证书报考者应提供教育部留学服务中心出具的学历学位认证书(认证书截止时间为2015年7月31日);<br />
　　6.152005岗位报考者应为中共党员。<br />
　　二、<strong>招聘岗位及要求</strong><br />
<table border="0" cellpadding="0" cellspacing="0" style="width:552px;" width="552">
	<tbody>
		<tr>
			<td style="width:72px;height:54px;">
				<strong>岗位</strong><br />
				<strong>代码</strong></td>
			<td style="width:120px;height:54px;">
				<strong>单位名称</strong></td>
			<td style="width:84px;height:54px;">
				<strong>招聘</strong><br />
				<strong>岗位</strong></td>
			<td style="width:48px;height:54px;">
				<strong>招聘人数</strong></td>
			<td style="width:120px;height:54px;">
				<strong>专业</strong></td>
			<td style="width:108px;height:54px;">
				<strong>学历学位</strong></td>
		</tr>
		<tr>
			<td style="width:72px;height:69px;">
				152001</td>
			<td style="width:120px;height:69px;">
				福建省中医药研究院</td>
			<td style="width:84px;height:69px;">
				财务科<br />
				工作人员</td>
			<td style="width:48px;height:69px;">
				2</td>
			<td style="width:120px;height:69px;">
				财政金融类、会计与审计类</td>
			<td style="width:108px;height:69px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
		<tr>
			<td style="width:72px;height:92px;">
				152002</td>
			<td style="width:120px;height:92px;">
				福建中医药大学附属人民医院（福建省人民医院）</td>
			<td style="width:84px;height:92px;">
				信息中心<br />
				工作人员</td>
			<td style="width:48px;height:92px;">
				1</td>
			<td style="width:120px;height:92px;">
				计算机科学与技术类</td>
			<td style="width:108px;height:92px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
		<tr>
			<td style="width:72px;height:145px;">
				152003</td>
			<td style="width:120px;height:145px;">
				福建中医药大学附属人民医院（福建省人民医院）</td>
			<td style="width:84px;height:145px;">
				后勤保障部工作人员</td>
			<td style="width:48px;height:145px;">
				1</td>
			<td style="width:120px;height:145px;">
				给水排水工程、给排水科学与工程、机电安装工程、电气工程及其自动化、建筑电气工程技术、给排水工程技术、消防工程技术、建筑水电技术</td>
			<td style="width:108px;height:145px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
		<tr>
			<td style="width:72px;height:75px;">
				152004</td>
			<td style="width:120px;height:75px;">
				福建中医药大学附属人民医院（福建省人民医院）</td>
			<td style="width:84px;height:75px;">
				后勤保障部工作人员</td>
			<td style="width:48px;height:75px;">
				1</td>
			<td style="width:120px;height:75px;">
				供热供燃气通风及空调工程、供热通风与卫生工程技术、供热通风与空调工程技术</td>
			<td style="width:108px;height:75px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
		<tr>
			<td style="width:72px;height:70px;">
				152005</td>
			<td style="width:120px;height:70px;">
				福建中医药大学附属康复医院</td>
			<td style="width:84px;height:70px;">
				监审科<br />
				工作人员</td>
			<td style="width:48px;height:70px;">
				1</td>
			<td style="width:120px;height:70px;">
				审计学、审计（实务）、财务管理、会计与审计、会计（学）、财务会计（教育）</td>
			<td style="width:108px;height:70px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
		<tr>
			<td style="width:72px;height:72px;">
				152006</td>
			<td style="width:120px;height:72px;">
				福建中医药大学附属康复医院</td>
			<td style="width:84px;height:72px;">
				网络中心<br />
				信息管理&nbsp;<br />
				工作人员</td>
			<td style="width:48px;height:72px;">
				1</td>
			<td style="width:120px;height:72px;">
				计算机科学与技术类</td>
			<td style="width:108px;height:72px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
		<tr>
			<td style="width:72px;height:83px;">
				152007</td>
			<td style="width:120px;height:83px;">
				福建中医药大学附属第三人民医院</td>
			<td style="width:84px;height:83px;">
				办公室<br />
				工作人员</td>
			<td style="width:48px;height:83px;">
				1</td>
			<td style="width:120px;height:83px;">
				新闻传播学类</td>
			<td style="width:108px;height:83px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
		<tr>
			<td style="width:72px;height:83px;">
				152008</td>
			<td style="width:120px;height:83px;">
				福建中医药大学附属第三人民医院</td>
			<td style="width:84px;height:83px;">
				人力资源科工作人员</td>
			<td style="width:48px;height:83px;">
				1</td>
			<td style="width:120px;height:83px;">
				人力资源管理、公共事业（事务）管理、行政管理、公共管理</td>
			<td style="width:108px;height:83px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
		<tr>
			<td style="width:72px;height:99px;">
				152009</td>
			<td style="width:120px;height:99px;">
				福建中医药大学附属第三人民医院</td>
			<td style="width:84px;height:99px;">
				慢性病与老年保健科工作人员</td>
			<td style="width:48px;height:99px;">
				1</td>
			<td style="width:120px;height:99px;">
				中医学类</td>
			<td style="width:108px;height:99px;">
				本科及以上学历，学士及以上学位</td>
		</tr>
	</tbody>
</table>
　
</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
