{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江绍兴科技馆选调3名科技辅导教师公告{/dede:field}
{dede:field name='title'}2015年浙江绍兴科技馆选调3名科技辅导教师公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江绍兴科技馆选调3名科技辅导教师公告</h2>
<strong>　　一、选调范围和名额</strong><br />
　　在绍兴市范围内的全额拨款事业单位在编工作人员中选调绍兴科技馆科技辅导教师3名。<br />
　　<strong>二、选调资格和条件(表格附后)<br />
　　三、选调程序</strong><br />
　　选调按照公开报名、资格审查、面试、考察、讨论决定、调动的程序进行。<br />
　　(一)公开报名<br />
　　报考人员需填写《绍兴科技馆选调科技辅导教师报名表》(表格附后)，以电子邮件形式报名，邮箱sx_kjzx@163.com，注明姓名和应聘职位。<br />
　　报名时间：即日起至 2015年5月6日<br />
　　(二)资格审核<br />
　　符合条件的应聘者将短信通知，按规定时间到规定地点进行现场资格审核，届时请提供身份证、学历证书、职称证书、相关资格证书、获奖证书原件并交复印件一份，工作经历及现单位同意报考有效证明，彩色2寸免冠近照1张。应聘人员必须保证提供资料真实有效。凡弄虚作假者，一经查实，取消应聘资格。<br />
　　时间：2015年5月10日12：30&mdash;16：30<br />
　　地点：绍兴科技馆一楼报告厅(绍兴市镜湖新区洋江西路528号)<br />
　　(三)面试<br />
　　资格审查通过人员参加面试。面试注重对应试人员能力素质、个性特征和岗位适应程度等方面的了解。<br />
　　时间：2015年5月16日。<br />
　　地点：待定<br />
　　(四)考察<br />
　　所有岗位按1：1比例从高分到低分确定面试对象进行考察。<br />
　　(五)讨论决定<br />
　　绍兴市科协党组根据面试成绩和考察情况，讨论确定选调对象。出现放弃情况的，缺额在面试成绩从高分到低分依次递补。<br />
　　(六)办理调动手续<br />
　　此次选调具体详情登录：绍兴人才网http://www.sxrc.com.cn、绍兴科普网www.sxkx.gov.cn<br />
　　联系电话：88009635、88009620<br />
　　绍兴科技馆<br />
　　选调科技辅导教师岗位要求一览表<br />
<table align="left" border="1" cellpadding="0" cellspacing="0" style="width:100%;">
	<tbody>
		<tr>
			<td style="width:70px;height:59px;">
				招聘岗位</td>
			<td style="width:28px;height:59px;">
				人数</td>
			<td style="width:105px;height:59px;">
				岗位职责</td>
			<td style="width:125px;height:59px;">
				学历和专业</td>
			<td style="width:206px;height:59px;">
				具体要求</td>
			<td style="width:89px;height:59px;">
				备注</td>
		</tr>
		<tr>
			<td style="width:70px;height:169px;">
				科学教师</td>
			<td style="width:28px;height:169px;">
				1</td>
			<td style="width:105px;height:169px;">
				青少年科技教育培训</td>
			<td style="width:125px;height:169px;">
				大学本科及以上学历，科学教育专业、物理学类、化学类、生物科学类专业。</td>
			<td style="width:206px;height:169px;">
				35周岁以下。熟悉青少年工作，有较强的语言表达能力。从事青少年科学、物理、化学、生物教育培训辅导工作2年及以上工作经历。（具有副高级专业技术职务及以上人员的最高年龄可放宽到45周岁）</td>
			<td style="width:89px;height:169px;">
				1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:70px;height:223px;">
				计算机<br />
				信息学<br />
				教师</td>
			<td style="width:28px;height:223px;">
				1</td>
			<td style="width:105px;height:223px;">
				青少年计算机信息学培训，组织全市青少年信息学竞赛</td>
			<td style="width:125px;height:223px;">
				大学本科及以上学历，科学教育专业、计算机类、数学类、物理学类、化学类、生物科学类专业。</td>
			<td style="width:206px;height:223px;">
				35周岁以下。有较强的语言表达能力和活动组织能力。从事计算机信息学教学培训辅导工作2年及以上工作经历。（有信息学竞赛获奖经历或辅导学生参加信息学竞赛获奖经历在同等条件下优先）</td>
			<td style="width:89px;height:223px;">
				1980年1月1日以后出生。</td>
		</tr>
		<tr>
			<td style="width:70px;height:217px;">
				机器人辅导<br />
				教师</td>
			<td style="width:28px;height:217px;">
				1</td>
			<td style="width:105px;height:217px;">
				青少年机器人培训，组织全市青少年机器人竞赛</td>
			<td style="width:125px;height:217px;">
				大学本科及以上学历，科学教育专业、计算机类、数学类、物理学类、化学类、生物科学类专业。</td>
			<td style="width:206px;height:217px;">
				35周岁以下，有较强的语言表达能力和活动组织能力。有机器人教学培训辅导工作经历。（有机器人竞赛获奖经历或辅导学生参加机器人竞赛获奖经历在同等条件下优先）</td>
			<td style="width:89px;height:217px;">
				1980年1月1日以后出生。</td>
		</tr>
	</tbody>
</table>
　　绍兴科技馆选调科技辅导教师报名表
</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
