{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建龙岩市中医院现场招聘医学类毕业生4人公告{/dede:field}
{dede:field name='title'}2015年福建龙岩市中医院现场招聘医学类毕业生4人公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建龙岩市中医院现场招聘医学类毕业生4人公告</h2>
　　根据《事业单位公开招聘人员暂行规定》(原人事部第6号令)及《龙岩市市直医疗卫生事业单位公开招聘工作人员考试实施办法》(龙人发〔2011〕26号)精神，我院决定于2015年4月17日到福建中医药大学附属人民医院(福建省福州市817中路602号)现场招聘硕士研究生以上毕业生充实到紧缺急需岗位。现将有关事项公告如下：<br />
　　<strong>一、基本条件</strong><br />
　　1.遵纪守法，品行端正，爱岗敬业，具有良好的思想道德和职业道德，热爱医学事业，在校期间未受过处分;<br />
　　2.身体健康，体检应符合《公务员录用体检通用标准(试行)》和卫生行业规定;<br />
　　3.年龄30周岁及以下指1984年4月17日及以后出生;<br />
　　4.符合招聘岗位所需的其他条件。<br />
　　<strong>二、岗位要求及人数</strong><br />
　　详见附件1<br />
　　<strong>三、招聘程序</strong><br />
　　(一)组织报名。应聘的应届毕业生须携带学生证、身份证原件和复印件及《大中专毕业生就业推荐表》、自荐材料等，应聘的往届毕业生须携带身份证、毕业证书、学位证书、报到证原件和复印件、自荐材料等，于2015年4月17日到福建中医药大学附属人民医院(福建省福州市817中路602号)现场填报《龙岩市市直医疗卫生单位招聘专业技术人员报名表》。<br />
　　(二)资格审核。由用人单位对报名情况进行审核。<br />
　　(三)考核办法。采用面试考核方式招聘，由用人单位组成面试考核小组，对符合招聘岗位要求的应聘者进行现场面试考核。<br />
　　(四)签订协议书。对拟聘用的毕业生由用人单位与其现场签订聘用协议书。<br />
　　(五)考察。根据实际情况调阅被考察者档案或参考被考察者工作单位(或毕业学校)的现实表现鉴定。<br />
　　(六)体检。由用人单位指定时间地点对考察合格的拟聘用人员进行体检，体检时拟聘用人员须携带毕业证、学位证、报到证等相关原件及复印件。体检标准参照《公务员录用体检通用标准(试行)》。<br />
　　(七)办理录用手续。体检合格者，在www.lyrsw.com(龙岩人事网)上进行公示，公示时间为7日。公示结束后，为公示无异议人员办理相关聘用手续。<br />
　<strong>　四、相关待遇</strong><br />
　　聘用人员享受国家统一规定的事业单位工作人员相应学历或专业技术职称人员的工资待遇和所在岗位津贴及福利。<br />
<strong>　　五、注意事项</strong><br />
　　1.工作人员应认真履行好职责，招聘工作做到信息公开，过程公开，结果公开，自觉接受纪检监察部门和社会各界的监督。<br />
　　2.考生必须在规定时间内参加报名和面试。<br />
　　<strong>六、联系方式</strong><br />
　　龙岩市中医院联系人：刘汉东13959040972<br />
　　1、2015年龙岩市中医院现场招聘岗位表<br />
<table border="0" cellpadding="0" cellspacing="0" style="width:100%;">
	<colgroup>
		<col span="10" />
	</colgroup>
	<tbody>
		<tr height="19">
			<td height="38" rowspan="2" style="width:72px;height:38px;">
				岗位 编码</td>
			<td rowspan="2" style="width:72px;">
				岗位名称</td>
			<td rowspan="2" style="width:72px;">
				招聘人数</td>
			<td colspan="7" style="width:504px;">
				所 需 资 格 条 件</td>
		</tr>
		<tr height="19">
			<td height="19" style="width:72px;height:19px;">
				最高年龄</td>
			<td style="width:72px;">
				性别</td>
			<td style="width:72px;">
				最低学历</td>
			<td style="width:72px;">
				最低学位</td>
			<td style="width:72px;">
				最低职称</td>
			<td style="width:72px;">
				需求专业</td>
			<td style="width:72px;">
				其他条件</td>
		</tr>
		<tr height="38">
			<td align="right" height="38" style="width:72px;height:38px;">
				4001</td>
			<td style="width:72px;">
				心内科医师</td>
			<td align="right" style="width:72px;">
				1</td>
			<td align="right" style="width:72px;">
				30</td>
			<td style="width:72px;">
				不限</td>
			<td style="width:72px;">
				研究生</td>
			<td style="width:72px;">
				硕士</td>
			<td style="width:72px;">
				不限</td>
			<td style="width:72px;">
				中西医结合临床</td>
			<td style="width:72px;">
				无</td>
		</tr>
		<tr height="38">
			<td align="right" height="38" style="width:72px;height:38px;">
				4002</td>
			<td style="width:72px;">
				脾胃病科医师</td>
			<td align="right" style="width:72px;">
				1</td>
			<td align="right" style="width:72px;">
				30</td>
			<td style="width:72px;">
				不限</td>
			<td style="width:72px;">
				研究生</td>
			<td style="width:72px;">
				硕士</td>
			<td style="width:72px;">
				不限</td>
			<td style="width:72px;">
				针灸推拿专业</td>
			<td style="width:72px;">
				无</td>
		</tr>
		<tr height="38">
			<td align="right" height="38" style="width:72px;height:38px;">
				4003</td>
			<td style="width:72px;">
				重症医学科</td>
			<td align="right" style="width:72px;">
				1</td>
			<td align="right" style="width:72px;">
				30</td>
			<td style="width:72px;">
				不限</td>
			<td style="width:72px;">
				研究生</td>
			<td style="width:72px;">
				硕士</td>
			<td style="width:72px;">
				不限</td>
			<td style="width:72px;">
				中医内科学</td>
			<td style="width:72px;">
				无</td>
		</tr>
		<tr height="38">
			<td align="right" height="38" style="width:72px;height:38px;">
				4004</td>
			<td style="width:72px;">
				针灸科医师</td>
			<td align="right" style="width:72px;">
				1</td>
			<td align="right" style="width:72px;">
				30</td>
			<td style="width:72px;">
				不限</td>
			<td style="width:72px;">
				研究生</td>
			<td style="width:72px;">
				硕士</td>
			<td style="width:72px;">
				不限</td>
			<td style="width:72px;">
				针灸推拿专业</td>
			<td style="width:72px;">
				无</td>
		</tr>
	</tbody>
</table>
　　龙岩市市直医疗卫生单位招聘专业技术人员报名表
</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
