{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江省嘉兴海宁消防大队人员招聘公告{/dede:field}
{dede:field name='title'}2015年浙江省嘉兴海宁消防大队人员招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江省嘉兴海宁消防大队人员招聘公告</h2>
<p>
	　　接处警岗位：</p>
<p>
	　<strong>　一、岗位描述：</strong></p>
<p>
	<strong>　</strong>　1、负责119指挥中心火警受理;</p>
<p>
	　　2、协助开展各类档案、台账制作、稿件编写;</p>
<p>
	　<strong>　二、岗位要求;</strong></p>
<p>
	　　1、遵守国家法律法规、部队规章制度和社会公德，无违法违纪行为;</p>
<p>
	　　2、高中以上学历，具有基础网络知识;</p>
<p>
	　　3、工作积极主动，要求上进，工作自主独立性强，具有一定的创新精神。工作责任心</p>
<p>
	　　强，爱岗敬业，具有较强的集体荣誉感;</p>
<p>
	　　4、要求具有海宁本地户口，会海宁地方方言，熟悉海宁市道路情况，语言沟通交际能</p>
<p>
	　　力、处事应变能力较强。</p>
<p>
	<strong>　　三、工作时间：12小时工作，做二休一</strong></p>
<p>
	<strong>　　四、薪资待遇：3.3万/年(含五险)</strong></p>
<p>
	　　宣传文职岗位：</p>
<p>
	　　一、岗位描述：</p>
<p>
	　　1、负责大队对外宣传工作;</p>
<p>
	　　2、协助开展稿件编写、活动策划、宣传档案制作。</p>
<p>
	　　二、岗位要求;</p>
<p>
	　　(一)拥护党的路线、方针、政策，忠于祖国，忠于社会主义，志愿从事消防工作;</p>
<p>
	　　(二)遵守国家法律和社会公德，品行端正，作风正派，无违法违纪行为;</p>
<p>
	　　(三)责任心较强，爱岗敬业，办事认真，吃苦耐劳，有团结协作精神;</p>
<p>
	　　(四)全日制大学本科以上文化程度的毕业生，中文及传播学专业;</p>
<p>
	　　(五)有较好的文字功底及摄影技术，会视频拍摄剪辑。</p>
<p>
	　　(六)有一定的活动策划和领导能力或从事文字工作经验在两年以上，新闻类专业毕业，</p>
<p>
	　　有在广电、报社等媒体工作经验或在相关宣传岗位做出过突出成绩的，可适当放宽条件并</p>
<p>
	　　优先考虑。</p>
<p>
	<strong>　　三、工作时间：8小时工作，正常双休。</strong></p>
<p>
	<strong>　　四、薪资待遇：3.3万/年(含五险)，稿费奖励另计。</strong></p>
<p>
	　　辅助执法文职岗位：</p>
<p>
	　<strong>　一、岗位描述：</strong></p>
<p>
	　　负责大队辅助执法工作;</p>
<p>
	　<strong>　二、岗位要求;</strong></p>
<p>
	　　(一 )拥护党的路线、方针、政策，忠于祖国，忠于社会主义，志愿从事消防工作;</p>
<p>
	　　(二)遵守国家法律和社会公德，品行端正，作风正派，无违法违纪行为;</p>
<p>
	　　(三)责任心较强，爱岗敬业，办事认真，吃苦耐劳，有团结协作精神;</p>
<p>
	　　(四)有一定的文字功底，建筑、法律、中文专业的可适当放宽条件</p>
<p>
	　　并优先考虑。</p>
<p>
	<strong>　　三、工作时间：8小时工作，正常双休。</strong></p>
<p>
	<strong>　　四、薪资待遇：3.3万/年(含五险)。</strong></p>
<p>
	　　联系电话：87073119</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
