{dede:field name='keywords'}江西,事业单位招聘{/dede:field}
{dede:field name='description'}2015年南昌大学抚州医学院招聘高层次人才公告{/dede:field}
{dede:field name='title'}2015年南昌大学抚州医学院招聘高层次人才公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　江西备考交流QQ群：186502481<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/jiangxi/sy" target="_blank"><span style="color: #0000ff">2015年江西省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年南昌大学抚州医学院招聘高层次人才公告</h2>
<strong>　　一、学院简介</strong><br />
　　南昌大学抚州医学院座落于以&ldquo;才子之乡&rdquo;、&ldquo;文化之邦&rdquo;著称的历史文化名城&mdash;&mdash;江西抚州市，位于风景秀丽的抚河之畔，占地面积650余亩，建筑面积23万余平方米。<br />
　　南昌大学抚州医学院是南昌大学五大校区之一，是南昌大学医学教育的组成部分，是培养医学专门实用型人才的教学型学院。现设有本科和专科两个层次的医学教育。其中本科有护理学、临床医学等专业;专科设有临床医学、护理学、口腔医学、药学、医学检验技术等专业。<br />
　　学院图书馆建筑面积1.36万平方米，阅览座位2000多个，纸质藏书25余万册，电子图书110余万册，全面共享校本部图书馆电子资源，开放了中国期刊网、万方数据知识服务平台和维普中文科技期刊等19种中文数据库;引进了ELSEVIER、EI、ISTP、SCI、PQDD和SPRINGER等50余种外文数据库。<br />
　　学院现有二所合作型附属医院，同时还在全国各地建立了150多家实习基地，能够充分满足各级、各专业学生的实践教学需求。<br />
　　现根据学院的发展需要,面向社会公开招聘具有硕士研究生以上学历学位的高层次人才。<br />
<strong>　　二、招聘岗位、人数和条件</strong><br />
<table border="1" cellpadding="0" cellspacing="0" style="width:100%;" width="100%">
	<tbody>
		<tr>
			<td style="width:17.44%;">
				招聘岗位</td>
			<td style="width:12.96%;">
				招聘人数</td>
			<td style="width:49.64%;">
				岗位条件</td>
			<td style="width:19.96%;">
				备注</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:17.44%;">
				病理教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				病理学与病理生理学（病理学方向）专业、全日制硕士研究生及以上学历学位</td>
			<td rowspan="2" style="width:19.96%;">
				全日制本科临床医学专业起点</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				病理学与病理生理学（病理生理学方向）专业、全日制硕士研究生及以上学历学位</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:17.44%;">
				药学教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				生药学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科为医学院校毕业</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				中药学专业、博士研究生学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:17.44%;">
				公共卫生教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				流行病与卫生统计学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科预防医学专业起点</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				劳动卫生与环境卫生学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科预防医学专业起点</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				生理教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				生理学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科医学专业起点</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				人解教研室教师岗</td>
			<td style="width:12.96%;">
				2</td>
			<td style="width:49.64%;">
				人体解剖与组织胚胎学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科医学专业起点</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				生化教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				生物化学与分子生物学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科起点，研究生为医学院校毕业</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				病原生物学与免疫学教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				免疫学或病原生物学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科医学专业起点</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				护理教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				护理学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				计算机与数理教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				理论物理专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科起点</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				口腔医学系教师岗</td>
			<td style="width:12.96%;">
				3</td>
			<td style="width:49.64%;">
				口腔临床医学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				第一学历为医学专业</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:17.44%;">
				内科学教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				内科学（传染病）专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				内科学（呼吸内科）专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				医学影像教研室教师岗</td>
			<td style="width:12.96%;">
				2</td>
			<td style="width:49.64%;">
				影像医学与核医学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				妇产科教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				妇产科学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				眼耳鼻喉科学教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				眼科学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:17.44%;">
				外科学教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				麻醉学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				外科学（普通外科）专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:17.44%;">
				外科学教研室教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				外科学（胸心血管外科）专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				外科学（神经外科学）专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td rowspan="4" style="width:17.44%;">
				实验教学部实验教师岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				病原生物学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科医学专业起点</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				护理学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				口腔基础医学或口腔临床医学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				病理学与病理生理学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科临床医学专业起点</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				教务处<br />
				管理岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				社会医学与卫生事业管理或公共卫生与预防医学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科医学专业起点</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				科研处<br />
				管理岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				医学类专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:17.44%;">
				心理健康教育中心管理岗</td>
			<td style="width:12.96%;">
				1</td>
			<td style="width:49.64%;">
				心理学专业、全日制硕士研究生及以上学历学位</td>
			<td style="width:19.96%;">
				全日制本科心理学专业起点</td>
		</tr>
	</tbody>
</table>
　　注：以上招聘岗位硕士研究生年龄不超过35周岁(1980年1月1日以后出生)，博士研究生年龄不超过45周岁(1970年1月1日以后出生)。
</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
