{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江桐乡市濮院镇中心幼儿园教师招聘公告{/dede:field}
{dede:field name='title'}2015年浙江桐乡市濮院镇中心幼儿园教师招聘公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江桐乡市濮院镇中心幼儿园教师招聘公告</h2>
<p>
	　　因园所发展需要，濮院镇中心幼儿园即日起公开招聘教师若干名，欢迎符合条件者持相关资料前来报名。</p>
<p>
	<strong>　　一、招聘条件</strong></p>
<p>
	　　1.专科以上学前教育专业毕业,有幼儿园教师资格证。</p>
<p>
	　　2.思想素质好，专业知识、专业技能扎实。</p>
<p>
	<strong>　　二、招聘时间及录用人数</strong></p>
<p>
	　　定于2015年4月底在本园内进行面试，符合条件者经面试、体检合格后择优录用若干名。</p>
<p>
	<strong>　　四、报名联系</strong></p>
<p>
	　　1.凡符合应聘条件的人员，须提供本人近期正面免冠照片1张，持本人真实有效的学历证书、身份证、教师资格证等材料前来报名。</p>
<p>
	　　2.联系人：黄老师：05 73&mdash;89389011 手机：13819336609 QQ：326584901</p>
<p>
	　　3.园址：桐乡市濮院镇红星路150号</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
