{dede:field name='keywords'}福建,事业单位招聘{/dede:field}
{dede:field name='description'}2015年福建龙岩财经学校编外招聘1人公告{/dede:field}
{dede:field name='title'}2015年福建龙岩财经学校编外招聘1人公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: #ff0000">　　福建备考交流QQ群：256675811<br />
<span style="color: #0000ff"><strong>　　</strong></span></span><strong><span style="color: #0000ff">备考推荐：</span><a href="http://v.huatu.com/fujian/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: #0000ff">2015年福建省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年福建龙岩财经学校编外招聘1人公告</h2>
<p>
	　　本着公开、平等、竞争、择优的原则，拟向社会公开招聘1名编制外工作人员。</p>
<p>
	<strong>　　一、报考资格</strong></p>
<p>
	　　1.拥护中国共产党的领导，热爱社会主义。</p>
<p>
	　　2.身体健康，遵纪守法，品行端正。</p>
<p>
	　　3.有较强的业务能力, 有较强的事业心和责任感。</p>
<p>
	　　4.符合招聘岗位所需具体条件。</p>
<p>
	<strong>　　二、招聘岗位、人数及岗位所需条件</strong></p>
<p>
	　　(一)招聘岗位及人数</p>
<p>
	　　物流实训设施管理员(男 )1名(需物流，电子商务专业)。</p>
<p>
	　　(二)招聘条件</p>
<p>
	　　1.全日制专科及以上学历;</p>
<p>
	　　2.年龄在35周岁以下(即1980年4月以后出生)。</p>
<p>
	<strong>　　三、报名事项</strong></p>
<p>
	　　1.报名时间：2015年4月7日至4月13日的正常上班时间，联系人：曾老师</p>
<p>
	　　联系电话：0597-2885305。</p>
<p>
	　　2.报名地点：龙岩财经学校人事科(办公楼三楼)。</p>
<p>
	　　3.报名办法： 现场报名。须携带以下材料：(1)本人身份证(或户口簿)、毕业证书原件和计生、综治证明;(2)近期二寸同底正面免冠彩照3张;(3)简历一份。</p>
<p>
	　　<strong>四、录用办法</strong></p>
<p>
	　　组织考试形式：综合面试，分值为100分。内容：面试主要测试综合分析能力、语言表达能力和应变能力 等。面试时间、地点及要求另行通知。</p>
<p>
	　<strong>　五、体检与考核</strong></p>
<p>
	　　1.根据综合考核成绩从高分到低分的顺序，确定第一名为体检对象。若拟录用人员因自己放弃，体检不合格及其它原因不能应聘，可按综合考核成绩依次递补。</p>
<p>
	　　2.体检参照福建省教育厅办理教师资格规定的有关项目体检，由我校组织，费用由参加体检者自理。</p>
<p>
	　　3.考核办法按有关规定执行。</p>
<p>
	<strong>　　六、聘用办法与待遇</strong></p>
<p>
	　　(一)聘用形式及聘用期限</p>
<p>
	　　聘用人员与福建省海峡派遣公司龙岩分公司签订劳动合同，合同期限两年，其中试用期3个月。</p>
<p>
	　　(二)待遇</p>
<p>
	　　聘用者由福建龙岩财经学校委托福建省海峡派遣公司龙岩分公司支付工资[月工资为基本工资1800元，另加绩效工资每月300元，(该部分每学期考核后发给)]并缴纳社会保险、医疗保险、工伤保险、失业保险、生育保险和住房公积金，自试用期起支付。</p>
<p style="text-align: right;">
	　　福建龙岩财经学校</p>
<p style="text-align: right;">
	　　2015年4月7日</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
