{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江国家动物博物馆展示馆讲解接待员招聘1人公告{/dede:field}
{dede:field name='title'}2015年浙江国家动物博物馆展示馆讲解接待员招聘1人公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江国家动物博物馆展示馆讲解接待员招聘1人公告</h2>
　　国家动物博物馆展示馆位于中国科学院奥运园区，隶属中国科学院动物研究所，是中国最大的动物专业博物馆，以宣传和普及动物科学知识为宗旨，宣传生态环境保护和人与自然和谐共处为理念，是中国科学院动物研究所面向社会、为广大人民群众服务的窗口。<br />
　　本馆展示面积5500平米，设有1个流动展厅、9个固定展厅和1个4D动感影院。其中9个固定展厅囊括了动物学的所有类群和基础知识，以大型景窗为主题重点突出了几个典型的生态环境，及其以此为栖息地的特有动物，展示了动物与环境的和谐一致，既有知识的科学性，又有丰富的趣味性和可视性。<br />
　　国家动物博物馆展示馆因工作需要现向社会公开招聘讲解接待员。<br />
　　招聘人数：1人<br />
　　工作地点：国家动物博物馆展示馆<br />
　　工作内容：讲解、接待、活动筹备以及博物馆日常管理工作<br />
　　工资待遇：享受中国科学院动物研究所人才派遣相关待遇<br />
　　招聘条件：<br />
　　1.性别：不限;年龄：原则上在25周岁以下;<br />
　　2.大学本科及以上学历;动物学或动物学相关专业优先考虑;<br />
　　3.中文要求能够讲普通话，具有较强的交流和较好的表达能力;<br />
　　4.体貌端庄。<br />
　　有相关工作或实习经验者条件可适当放宽。<br />
　　有意应聘者请于2015年4月16日前将应聘表格填好，发至国家动物博物馆展示馆。邮件地址： sunxin@ioz.ac.cn<br />
　　应聘报名表<br />
<table border="1" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width:59px;height:26px;">
				姓 名</td>
			<td colspan="3" style="width:109px;height:26px;">
				&nbsp;</td>
			<td style="width:47px;height:26px;">
				性别</td>
			<td colspan="3" style="width:84px;height:26px;">
				&nbsp;</td>
			<td colspan="3" style="width:84px;height:26px;">
				出生日期</td>
			<td colspan="4" style="width:133px;height:26px;">
				&nbsp;</td>
			<td rowspan="6" style="width:144px;height:26px;">
				&nbsp;<br />
				照 片<br />
				(可另附半身免妆照片)</td>
		</tr>
		<tr>
			<td style="width:59px;height:30px;">
				籍 贯</td>
			<td colspan="3" style="width:109px;height:30px;">
				&nbsp;</td>
			<td style="width:47px;height:30px;">
				民 族</td>
			<td colspan="3" style="width:84px;height:30px;">
				&nbsp;</td>
			<td colspan="3" style="width:84px;height:30px;">
				学 历</td>
			<td colspan="4" style="width:133px;height:30px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="4" style="width:168px;height:30px;">
				户籍所在地</td>
			<td colspan="11" style="width:348px;height:30px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="4" style="width:168px;height:29px;">
				毕业学校及专业</td>
			<td colspan="11" style="width:348px;height:29px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="2" style="width:86px;height:29px;">
				学位</td>
			<td colspan="2" style="width:82px;height:29px;">
				&nbsp;</td>
			<td colspan="3" style="width:90px;height:29px;">
				英语水平</td>
			<td colspan="2" style="width:86px;height:29px;">
				&nbsp;</td>
			<td colspan="3" style="width:86px;height:29px;">
				爱好</td>
			<td colspan="3" style="width:86px;height:29px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="4" style="width:168px;height:30px;">
				联系地址</td>
			<td colspan="11" style="width:348px;height:30px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="4" style="width:168px;height:32px;">
				身份证号码</td>
			<td colspan="10" style="width:277px;height:32px;">
				&nbsp;</td>
			<td style="width:71px;height:32px;">
				身高（cm）</td>
			<td style="width:144px;height:32px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td rowspan="2" style="width:59px;height:33px;">
				联系<br />
				方式</td>
			<td colspan="3" style="width:109px;height:33px;">
				联系地址</td>
			<td colspan="10" style="width:277px;height:33px;">
				&nbsp;</td>
			<td style="width:71px;height:33px;">
				邮 编</td>
			<td style="width:144px;height:33px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="3" style="width:109px;height:31px;">
				联系电话</td>
			<td colspan="10" style="width:277px;height:31px;">
				&nbsp;</td>
			<td style="width:71px;height:31px;">
				E-mail</td>
			<td style="width:144px;height:31px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:59px;height:113px;">
				&nbsp;<br />
				个<br />
				人<br />
				简<br />
				历<br />
				&nbsp;</td>
			<td colspan="15" style="width:601px;height:113px;">
				&nbsp;<br />
				&nbsp;<br />
				&nbsp;</td>
		</tr>
		<tr>
			<td rowspan="5" style="width:59px;height:31px;">
				家<br />
				庭<br />
				主<br />
				要<br />
				成<br />
				员</td>
			<td colspan="2" style="width:61px;height:31px;">
				关系</td>
			<td colspan="3" style="width:108px;height:31px;">
				居住地（省、市）</td>
			<td colspan="4" style="width:120px;height:31px;">
				工作单位</td>
			<td colspan="3" style="width:96px;height:31px;">
				职务或职称</td>
			<td colspan="3" style="width:216px;height:31px;">
				联系方式（电话、E-Mail等）</td>
		</tr>
		<tr>
			<td colspan="2" style="width:61px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:108px;height:31px;">
				&nbsp;</td>
			<td colspan="4" style="width:120px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:96px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:216px;height:31px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="2" style="width:61px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:108px;height:31px;">
				&nbsp;</td>
			<td colspan="4" style="width:120px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:96px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:216px;height:31px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="2" style="width:61px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:108px;height:31px;">
				&nbsp;</td>
			<td colspan="4" style="width:120px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:96px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:216px;height:31px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td colspan="2" style="width:61px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:108px;height:31px;">
				&nbsp;</td>
			<td colspan="4" style="width:120px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:96px;height:31px;">
				&nbsp;</td>
			<td colspan="3" style="width:216px;height:31px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:59px;height:78px;">
				自<br />
				我<br />
				简<br />
				介</td>
			<td colspan="15" style="width:601px;height:78px;">
				&nbsp;</td>
		</tr>
		<tr>
			<td style="width:59px;height:129px;">
				备<br />
				&nbsp;<br />
				注</td>
			<td colspan="15" style="width:601px;height:129px;">
				&nbsp;</td>
		</tr>
		<tr height="0">
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
			<td>
				&nbsp;</td>
		</tr>
	</tbody>
</table>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
