{dede:field name='keywords'}浙江,事业单位招聘{/dede:field}
{dede:field name='description'}2015年浙江杭州市西湖区紫荆幼儿园招聘10人公告{/dede:field}
{dede:field name='title'}2015年浙江杭州市西湖区紫荆幼儿园招聘10人公告{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<span style="color: rgb(255,0,0)">　　浙江备考交流QQ群：247113978<br />
<span style="color: rgb(0,0,255)"><strong>　　</strong></span></span><strong><span style="color: rgb(0,0,255)">备考推荐：</span><a href="http://v.huatu.com/zhejiang/sy" style="color: rgb(0,0,204); text-decoration: none" target="_blank"><span style="color: rgb(0,0,255)">2015年浙江省事业单位考试名师网络课程班</span></a></strong>
<hr />
<h2 style="text-align: center;">
	2015年浙江杭州市西湖区紫荆幼儿园招聘10人公告</h2>
<p>
	　　杭州市西湖区紫荆幼儿园隶属于西湖区教育局。现拥有紫荆、诚园两个园区。快乐紫荆：成立于2005年5月，座落在西湖区紫荆花路290号，毗邻西溪湿地和浙大紫金港校区，是西湖区教育局直属的浙江省一级和杭州市甲级幼儿园。园内环境优美、绿草茵茵，现有大、中、小17个班的规模。品质诚园：创建于2013年7月，于2014年9月正式开园，地处文一西路环境优雅、高端大气的西溪诚园小区内，毗邻西溪湿地，隶属于西湖区教育局，具有16个班的规模。</p>
<p>
	　　现因幼儿园发展需要，诚聘以下人员：</p>
<p>
	　　<strong>一、 幼儿教师岗位6名：</strong></p>
<p>
	　　应聘条件：</p>
<p>
	　　1.热爱幼教事业，工作责任心强、善于合作、乐于奉献。</p>
<p>
	　　2.学前教育大专或以上学历，有教师资格证，在职或应届毕业生均可。</p>
<p>
	　　3.有工作经验、获区级以上各类荣誉或优秀应届毕业生优先。</p>
<p>
	　　4.应聘者需提供本人简历，学历、普通话、计算机等级证书，荣誉证书等相关证件的复印件。</p>
<p>
	　<strong>　二、保育员岗位4名：</strong></p>
<p>
	　　应聘条件：</p>
<p>
	　　身体健康，责任心强，喜欢孩子，善于沟通，有保育员上岗证优先。</p>
<p>
	　　真诚欢迎您的加入，我们将为您提供发展的平台!</p>
<p>
	　　地 址：紫荆园区：西湖区紫荆花路290号</p>
<p>
	　　诚园园区：西湖区蒋村新区紫霞街8号</p>
<p>
	　　联系电话：周老师 88939330 13750849792</p>
<p>
	　　张老师 86693792 13735494228</p>
<p>
	　　电子邮箱：271166928@qq.com;465403328@qq.com</p>
<p style="text-align: right;">
	　　杭州市西湖区紫荆幼儿园</p>
<p style="text-align: right;">
	　　2015年4月</p>

</section><!--文章正文结束-->{/dede:field}
{dede:field name='litpic'}{/dede:field}
