<?php
$z[0]=Array("global","",169,203);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",416,441);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n          <li><a href='[field:typeurl function='str_replace(\"index.htm\",\"\",@me)'/]'>[field:typename/]</a></li>",459,684);
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li class='cur'><a href='~typelink~'>~typename~</a> </li>";

?>